// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package madmin

import (
	"github.com/shirou/gopsutil/v4/cpu"
	"github.com/shirou/gopsutil/v4/load"
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *CPUMetrics) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint16 /* 12 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "collected":
			z.CollectedAt, err = dc.ReadTimeUTC()
			if err != nil {
				err = msgp.WrapError(err, "CollectedAt")
				return
			}
		case "nodes":
			z.Nodes, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Nodes")
				return
			}
		case "timesStat":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "TimesStat")
					return
				}
				z.TimesStat = nil
			} else {
				if z.TimesStat == nil {
					z.TimesStat = new(cpu.TimesStat)
				}
				err = (*cpuTimesStat)(z.TimesStat).DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "TimesStat")
					return
				}
			}
		case "loadStat":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "LoadStat")
					return
				}
				z.LoadStat = nil
			} else {
				if z.LoadStat == nil {
					z.LoadStat = new(load.AvgStat)
				}
				err = (*loadAvgStat)(z.LoadStat).DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "LoadStat")
					return
				}
			}
		case "cpuCount":
			z.CPUCount, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "CPUCount")
				return
			}
		case "cpu_by_model":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "CPUByModel")
				return
			}
			if z.CPUByModel == nil {
				z.CPUByModel = make(map[string]int, zb0002)
			} else if len(z.CPUByModel) > 0 {
				clear(z.CPUByModel)
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "CPUByModel")
					return
				}
				var za0002 int
				za0002, err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "CPUByModel", za0001)
					return
				}
				z.CPUByModel[za0001] = za0002
			}
			zb0001Mask |= 0x1
		case "total_mhz":
			z.TotalMhz, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "TotalMhz")
				return
			}
			zb0001Mask |= 0x2
		case "total_cores":
			z.TotalCores, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "TotalCores")
				return
			}
			zb0001Mask |= 0x4
		case "total_cache_size":
			z.TotalCacheSize, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "TotalCacheSize")
				return
			}
			zb0001Mask |= 0x8
		case "freq_stats_count":
			z.FreqStatsCount, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "FreqStatsCount")
				return
			}
			zb0001Mask |= 0x10
		case "governor_freq":
			var zb0003 uint32
			zb0003, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "GovernorFreq")
				return
			}
			if z.GovernorFreq == nil {
				z.GovernorFreq = make(map[string]int, zb0003)
			} else if len(z.GovernorFreq) > 0 {
				clear(z.GovernorFreq)
			}
			for zb0003 > 0 {
				zb0003--
				var za0003 string
				za0003, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "GovernorFreq")
					return
				}
				var za0004 int
				za0004, err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "GovernorFreq", za0003)
					return
				}
				z.GovernorFreq[za0003] = za0004
			}
			zb0001Mask |= 0x20
		case "total_current_freq":
			z.TotalCurrentFreq, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "TotalCurrentFreq")
				return
			}
			zb0001Mask |= 0x40
		case "total_scaling_current_freq":
			z.TotalScalingCurrentFreq, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "TotalScalingCurrentFreq")
				return
			}
			zb0001Mask |= 0x80
		case "min_freq":
			z.MinCPUInfoFreq, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "MinCPUInfoFreq")
				return
			}
			zb0001Mask |= 0x100
		case "max_freq":
			z.MaxCPUInfoFreq, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "MaxCPUInfoFreq")
				return
			}
			zb0001Mask |= 0x200
		case "min_scaling_freq":
			z.MinScalingFreq, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "MinScalingFreq")
				return
			}
			zb0001Mask |= 0x400
		case "max_scaling_freq":
			z.MaxScalingFreq, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "MaxScalingFreq")
				return
			}
			zb0001Mask |= 0x800
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0xfff {
		if (zb0001Mask & 0x1) == 0 {
			z.CPUByModel = nil
		}
		if (zb0001Mask & 0x2) == 0 {
			z.TotalMhz = 0
		}
		if (zb0001Mask & 0x4) == 0 {
			z.TotalCores = 0
		}
		if (zb0001Mask & 0x8) == 0 {
			z.TotalCacheSize = 0
		}
		if (zb0001Mask & 0x10) == 0 {
			z.FreqStatsCount = 0
		}
		if (zb0001Mask & 0x20) == 0 {
			z.GovernorFreq = nil
		}
		if (zb0001Mask & 0x40) == 0 {
			z.TotalCurrentFreq = 0
		}
		if (zb0001Mask & 0x80) == 0 {
			z.TotalScalingCurrentFreq = 0
		}
		if (zb0001Mask & 0x100) == 0 {
			z.MinCPUInfoFreq = 0
		}
		if (zb0001Mask & 0x200) == 0 {
			z.MaxCPUInfoFreq = 0
		}
		if (zb0001Mask & 0x400) == 0 {
			z.MinScalingFreq = 0
		}
		if (zb0001Mask & 0x800) == 0 {
			z.MaxScalingFreq = 0
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *CPUMetrics) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(17)
	var zb0001Mask uint32 /* 17 bits */
	_ = zb0001Mask
	if z.CPUByModel == nil {
		zb0001Len--
		zb0001Mask |= 0x20
	}
	if z.TotalMhz == 0 {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	if z.TotalCores == 0 {
		zb0001Len--
		zb0001Mask |= 0x80
	}
	if z.TotalCacheSize == 0 {
		zb0001Len--
		zb0001Mask |= 0x100
	}
	if z.FreqStatsCount == 0 {
		zb0001Len--
		zb0001Mask |= 0x200
	}
	if z.GovernorFreq == nil {
		zb0001Len--
		zb0001Mask |= 0x400
	}
	if z.TotalCurrentFreq == 0 {
		zb0001Len--
		zb0001Mask |= 0x800
	}
	if z.TotalScalingCurrentFreq == 0 {
		zb0001Len--
		zb0001Mask |= 0x1000
	}
	if z.MinCPUInfoFreq == 0 {
		zb0001Len--
		zb0001Mask |= 0x2000
	}
	if z.MaxCPUInfoFreq == 0 {
		zb0001Len--
		zb0001Mask |= 0x4000
	}
	if z.MinScalingFreq == 0 {
		zb0001Len--
		zb0001Mask |= 0x8000
	}
	if z.MaxScalingFreq == 0 {
		zb0001Len--
		zb0001Mask |= 0x10000
	}
	// variable map header, size zb0001Len
	err = en.WriteMapHeader(zb0001Len)
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "collected"
		err = en.Append(0xa9, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64)
		if err != nil {
			return
		}
		err = en.WriteTime(z.CollectedAt)
		if err != nil {
			err = msgp.WrapError(err, "CollectedAt")
			return
		}
		// write "nodes"
		err = en.Append(0xa5, 0x6e, 0x6f, 0x64, 0x65, 0x73)
		if err != nil {
			return
		}
		err = en.WriteInt(z.Nodes)
		if err != nil {
			err = msgp.WrapError(err, "Nodes")
			return
		}
		// write "timesStat"
		err = en.Append(0xa9, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74)
		if err != nil {
			return
		}
		if z.TimesStat == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = (*cpuTimesStat)(z.TimesStat).EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "TimesStat")
				return
			}
		}
		// write "loadStat"
		err = en.Append(0xa8, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74)
		if err != nil {
			return
		}
		if z.LoadStat == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = (*loadAvgStat)(z.LoadStat).EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "LoadStat")
				return
			}
		}
		// write "cpuCount"
		err = en.Append(0xa8, 0x63, 0x70, 0x75, 0x43, 0x6f, 0x75, 0x6e, 0x74)
		if err != nil {
			return
		}
		err = en.WriteInt(z.CPUCount)
		if err != nil {
			err = msgp.WrapError(err, "CPUCount")
			return
		}
		if (zb0001Mask & 0x20) == 0 { // if not omitted
			// write "cpu_by_model"
			err = en.Append(0xac, 0x63, 0x70, 0x75, 0x5f, 0x62, 0x79, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c)
			if err != nil {
				return
			}
			err = en.WriteMapHeader(uint32(len(z.CPUByModel)))
			if err != nil {
				err = msgp.WrapError(err, "CPUByModel")
				return
			}
			for za0001, za0002 := range z.CPUByModel {
				err = en.WriteString(za0001)
				if err != nil {
					err = msgp.WrapError(err, "CPUByModel")
					return
				}
				err = en.WriteInt(za0002)
				if err != nil {
					err = msgp.WrapError(err, "CPUByModel", za0001)
					return
				}
			}
		}
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// write "total_mhz"
			err = en.Append(0xa9, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6d, 0x68, 0x7a)
			if err != nil {
				return
			}
			err = en.WriteFloat64(z.TotalMhz)
			if err != nil {
				err = msgp.WrapError(err, "TotalMhz")
				return
			}
		}
		if (zb0001Mask & 0x80) == 0 { // if not omitted
			// write "total_cores"
			err = en.Append(0xab, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x73)
			if err != nil {
				return
			}
			err = en.WriteInt(z.TotalCores)
			if err != nil {
				err = msgp.WrapError(err, "TotalCores")
				return
			}
		}
		if (zb0001Mask & 0x100) == 0 { // if not omitted
			// write "total_cache_size"
			err = en.Append(0xb0, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.TotalCacheSize)
			if err != nil {
				err = msgp.WrapError(err, "TotalCacheSize")
				return
			}
		}
		if (zb0001Mask & 0x200) == 0 { // if not omitted
			// write "freq_stats_count"
			err = en.Append(0xb0, 0x66, 0x72, 0x65, 0x71, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74)
			if err != nil {
				return
			}
			err = en.WriteInt(z.FreqStatsCount)
			if err != nil {
				err = msgp.WrapError(err, "FreqStatsCount")
				return
			}
		}
		if (zb0001Mask & 0x400) == 0 { // if not omitted
			// write "governor_freq"
			err = en.Append(0xad, 0x67, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x6f, 0x72, 0x5f, 0x66, 0x72, 0x65, 0x71)
			if err != nil {
				return
			}
			err = en.WriteMapHeader(uint32(len(z.GovernorFreq)))
			if err != nil {
				err = msgp.WrapError(err, "GovernorFreq")
				return
			}
			for za0003, za0004 := range z.GovernorFreq {
				err = en.WriteString(za0003)
				if err != nil {
					err = msgp.WrapError(err, "GovernorFreq")
					return
				}
				err = en.WriteInt(za0004)
				if err != nil {
					err = msgp.WrapError(err, "GovernorFreq", za0003)
					return
				}
			}
		}
		if (zb0001Mask & 0x800) == 0 { // if not omitted
			// write "total_current_freq"
			err = en.Append(0xb2, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x66, 0x72, 0x65, 0x71)
			if err != nil {
				return
			}
			err = en.WriteUint64(z.TotalCurrentFreq)
			if err != nil {
				err = msgp.WrapError(err, "TotalCurrentFreq")
				return
			}
		}
		if (zb0001Mask & 0x1000) == 0 { // if not omitted
			// write "total_scaling_current_freq"
			err = en.Append(0xba, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x66, 0x72, 0x65, 0x71)
			if err != nil {
				return
			}
			err = en.WriteUint64(z.TotalScalingCurrentFreq)
			if err != nil {
				err = msgp.WrapError(err, "TotalScalingCurrentFreq")
				return
			}
		}
		if (zb0001Mask & 0x2000) == 0 { // if not omitted
			// write "min_freq"
			err = en.Append(0xa8, 0x6d, 0x69, 0x6e, 0x5f, 0x66, 0x72, 0x65, 0x71)
			if err != nil {
				return
			}
			err = en.WriteUint64(z.MinCPUInfoFreq)
			if err != nil {
				err = msgp.WrapError(err, "MinCPUInfoFreq")
				return
			}
		}
		if (zb0001Mask & 0x4000) == 0 { // if not omitted
			// write "max_freq"
			err = en.Append(0xa8, 0x6d, 0x61, 0x78, 0x5f, 0x66, 0x72, 0x65, 0x71)
			if err != nil {
				return
			}
			err = en.WriteUint64(z.MaxCPUInfoFreq)
			if err != nil {
				err = msgp.WrapError(err, "MaxCPUInfoFreq")
				return
			}
		}
		if (zb0001Mask & 0x8000) == 0 { // if not omitted
			// write "min_scaling_freq"
			err = en.Append(0xb0, 0x6d, 0x69, 0x6e, 0x5f, 0x73, 0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x66, 0x72, 0x65, 0x71)
			if err != nil {
				return
			}
			err = en.WriteUint64(z.MinScalingFreq)
			if err != nil {
				err = msgp.WrapError(err, "MinScalingFreq")
				return
			}
		}
		if (zb0001Mask & 0x10000) == 0 { // if not omitted
			// write "max_scaling_freq"
			err = en.Append(0xb0, 0x6d, 0x61, 0x78, 0x5f, 0x73, 0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x66, 0x72, 0x65, 0x71)
			if err != nil {
				return
			}
			err = en.WriteUint64(z.MaxScalingFreq)
			if err != nil {
				err = msgp.WrapError(err, "MaxScalingFreq")
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *CPUMetrics) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(17)
	var zb0001Mask uint32 /* 17 bits */
	_ = zb0001Mask
	if z.CPUByModel == nil {
		zb0001Len--
		zb0001Mask |= 0x20
	}
	if z.TotalMhz == 0 {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	if z.TotalCores == 0 {
		zb0001Len--
		zb0001Mask |= 0x80
	}
	if z.TotalCacheSize == 0 {
		zb0001Len--
		zb0001Mask |= 0x100
	}
	if z.FreqStatsCount == 0 {
		zb0001Len--
		zb0001Mask |= 0x200
	}
	if z.GovernorFreq == nil {
		zb0001Len--
		zb0001Mask |= 0x400
	}
	if z.TotalCurrentFreq == 0 {
		zb0001Len--
		zb0001Mask |= 0x800
	}
	if z.TotalScalingCurrentFreq == 0 {
		zb0001Len--
		zb0001Mask |= 0x1000
	}
	if z.MinCPUInfoFreq == 0 {
		zb0001Len--
		zb0001Mask |= 0x2000
	}
	if z.MaxCPUInfoFreq == 0 {
		zb0001Len--
		zb0001Mask |= 0x4000
	}
	if z.MinScalingFreq == 0 {
		zb0001Len--
		zb0001Mask |= 0x8000
	}
	if z.MaxScalingFreq == 0 {
		zb0001Len--
		zb0001Mask |= 0x10000
	}
	// variable map header, size zb0001Len
	o = msgp.AppendMapHeader(o, zb0001Len)

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// string "collected"
		o = append(o, 0xa9, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64)
		o = msgp.AppendTime(o, z.CollectedAt)
		// string "nodes"
		o = append(o, 0xa5, 0x6e, 0x6f, 0x64, 0x65, 0x73)
		o = msgp.AppendInt(o, z.Nodes)
		// string "timesStat"
		o = append(o, 0xa9, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74)
		if z.TimesStat == nil {
			o = msgp.AppendNil(o)
		} else {
			o, err = (*cpuTimesStat)(z.TimesStat).MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, "TimesStat")
				return
			}
		}
		// string "loadStat"
		o = append(o, 0xa8, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74)
		if z.LoadStat == nil {
			o = msgp.AppendNil(o)
		} else {
			o, err = (*loadAvgStat)(z.LoadStat).MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, "LoadStat")
				return
			}
		}
		// string "cpuCount"
		o = append(o, 0xa8, 0x63, 0x70, 0x75, 0x43, 0x6f, 0x75, 0x6e, 0x74)
		o = msgp.AppendInt(o, z.CPUCount)
		if (zb0001Mask & 0x20) == 0 { // if not omitted
			// string "cpu_by_model"
			o = append(o, 0xac, 0x63, 0x70, 0x75, 0x5f, 0x62, 0x79, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c)
			o = msgp.AppendMapHeader(o, uint32(len(z.CPUByModel)))
			for za0001, za0002 := range z.CPUByModel {
				o = msgp.AppendString(o, za0001)
				o = msgp.AppendInt(o, za0002)
			}
		}
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// string "total_mhz"
			o = append(o, 0xa9, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6d, 0x68, 0x7a)
			o = msgp.AppendFloat64(o, z.TotalMhz)
		}
		if (zb0001Mask & 0x80) == 0 { // if not omitted
			// string "total_cores"
			o = append(o, 0xab, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x73)
			o = msgp.AppendInt(o, z.TotalCores)
		}
		if (zb0001Mask & 0x100) == 0 { // if not omitted
			// string "total_cache_size"
			o = append(o, 0xb0, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65)
			o = msgp.AppendInt64(o, z.TotalCacheSize)
		}
		if (zb0001Mask & 0x200) == 0 { // if not omitted
			// string "freq_stats_count"
			o = append(o, 0xb0, 0x66, 0x72, 0x65, 0x71, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74)
			o = msgp.AppendInt(o, z.FreqStatsCount)
		}
		if (zb0001Mask & 0x400) == 0 { // if not omitted
			// string "governor_freq"
			o = append(o, 0xad, 0x67, 0x6f, 0x76, 0x65, 0x72, 0x6e, 0x6f, 0x72, 0x5f, 0x66, 0x72, 0x65, 0x71)
			o = msgp.AppendMapHeader(o, uint32(len(z.GovernorFreq)))
			for za0003, za0004 := range z.GovernorFreq {
				o = msgp.AppendString(o, za0003)
				o = msgp.AppendInt(o, za0004)
			}
		}
		if (zb0001Mask & 0x800) == 0 { // if not omitted
			// string "total_current_freq"
			o = append(o, 0xb2, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x66, 0x72, 0x65, 0x71)
			o = msgp.AppendUint64(o, z.TotalCurrentFreq)
		}
		if (zb0001Mask & 0x1000) == 0 { // if not omitted
			// string "total_scaling_current_freq"
			o = append(o, 0xba, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x66, 0x72, 0x65, 0x71)
			o = msgp.AppendUint64(o, z.TotalScalingCurrentFreq)
		}
		if (zb0001Mask & 0x2000) == 0 { // if not omitted
			// string "min_freq"
			o = append(o, 0xa8, 0x6d, 0x69, 0x6e, 0x5f, 0x66, 0x72, 0x65, 0x71)
			o = msgp.AppendUint64(o, z.MinCPUInfoFreq)
		}
		if (zb0001Mask & 0x4000) == 0 { // if not omitted
			// string "max_freq"
			o = append(o, 0xa8, 0x6d, 0x61, 0x78, 0x5f, 0x66, 0x72, 0x65, 0x71)
			o = msgp.AppendUint64(o, z.MaxCPUInfoFreq)
		}
		if (zb0001Mask & 0x8000) == 0 { // if not omitted
			// string "min_scaling_freq"
			o = append(o, 0xb0, 0x6d, 0x69, 0x6e, 0x5f, 0x73, 0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x66, 0x72, 0x65, 0x71)
			o = msgp.AppendUint64(o, z.MinScalingFreq)
		}
		if (zb0001Mask & 0x10000) == 0 { // if not omitted
			// string "max_scaling_freq"
			o = append(o, 0xb0, 0x6d, 0x61, 0x78, 0x5f, 0x73, 0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x66, 0x72, 0x65, 0x71)
			o = msgp.AppendUint64(o, z.MaxScalingFreq)
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CPUMetrics) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint16 /* 12 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "collected":
			z.CollectedAt, bts, err = msgp.ReadTimeUTCBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CollectedAt")
				return
			}
		case "nodes":
			z.Nodes, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Nodes")
				return
			}
		case "timesStat":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.TimesStat = nil
			} else {
				if z.TimesStat == nil {
					z.TimesStat = new(cpu.TimesStat)
				}
				bts, err = (*cpuTimesStat)(z.TimesStat).UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "TimesStat")
					return
				}
			}
		case "loadStat":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.LoadStat = nil
			} else {
				if z.LoadStat == nil {
					z.LoadStat = new(load.AvgStat)
				}
				bts, err = (*loadAvgStat)(z.LoadStat).UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "LoadStat")
					return
				}
			}
		case "cpuCount":
			z.CPUCount, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CPUCount")
				return
			}
		case "cpu_by_model":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CPUByModel")
				return
			}
			if z.CPUByModel == nil {
				z.CPUByModel = make(map[string]int, zb0002)
			} else if len(z.CPUByModel) > 0 {
				clear(z.CPUByModel)
			}
			for zb0002 > 0 {
				var za0002 int
				zb0002--
				var za0001 string
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "CPUByModel")
					return
				}
				za0002, bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "CPUByModel", za0001)
					return
				}
				z.CPUByModel[za0001] = za0002
			}
			zb0001Mask |= 0x1
		case "total_mhz":
			z.TotalMhz, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TotalMhz")
				return
			}
			zb0001Mask |= 0x2
		case "total_cores":
			z.TotalCores, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TotalCores")
				return
			}
			zb0001Mask |= 0x4
		case "total_cache_size":
			z.TotalCacheSize, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TotalCacheSize")
				return
			}
			zb0001Mask |= 0x8
		case "freq_stats_count":
			z.FreqStatsCount, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "FreqStatsCount")
				return
			}
			zb0001Mask |= 0x10
		case "governor_freq":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "GovernorFreq")
				return
			}
			if z.GovernorFreq == nil {
				z.GovernorFreq = make(map[string]int, zb0003)
			} else if len(z.GovernorFreq) > 0 {
				clear(z.GovernorFreq)
			}
			for zb0003 > 0 {
				var za0004 int
				zb0003--
				var za0003 string
				za0003, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "GovernorFreq")
					return
				}
				za0004, bts, err = msgp.ReadIntBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "GovernorFreq", za0003)
					return
				}
				z.GovernorFreq[za0003] = za0004
			}
			zb0001Mask |= 0x20
		case "total_current_freq":
			z.TotalCurrentFreq, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TotalCurrentFreq")
				return
			}
			zb0001Mask |= 0x40
		case "total_scaling_current_freq":
			z.TotalScalingCurrentFreq, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TotalScalingCurrentFreq")
				return
			}
			zb0001Mask |= 0x80
		case "min_freq":
			z.MinCPUInfoFreq, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "MinCPUInfoFreq")
				return
			}
			zb0001Mask |= 0x100
		case "max_freq":
			z.MaxCPUInfoFreq, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "MaxCPUInfoFreq")
				return
			}
			zb0001Mask |= 0x200
		case "min_scaling_freq":
			z.MinScalingFreq, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "MinScalingFreq")
				return
			}
			zb0001Mask |= 0x400
		case "max_scaling_freq":
			z.MaxScalingFreq, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "MaxScalingFreq")
				return
			}
			zb0001Mask |= 0x800
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0xfff {
		if (zb0001Mask & 0x1) == 0 {
			z.CPUByModel = nil
		}
		if (zb0001Mask & 0x2) == 0 {
			z.TotalMhz = 0
		}
		if (zb0001Mask & 0x4) == 0 {
			z.TotalCores = 0
		}
		if (zb0001Mask & 0x8) == 0 {
			z.TotalCacheSize = 0
		}
		if (zb0001Mask & 0x10) == 0 {
			z.FreqStatsCount = 0
		}
		if (zb0001Mask & 0x20) == 0 {
			z.GovernorFreq = nil
		}
		if (zb0001Mask & 0x40) == 0 {
			z.TotalCurrentFreq = 0
		}
		if (zb0001Mask & 0x80) == 0 {
			z.TotalScalingCurrentFreq = 0
		}
		if (zb0001Mask & 0x100) == 0 {
			z.MinCPUInfoFreq = 0
		}
		if (zb0001Mask & 0x200) == 0 {
			z.MaxCPUInfoFreq = 0
		}
		if (zb0001Mask & 0x400) == 0 {
			z.MinScalingFreq = 0
		}
		if (zb0001Mask & 0x800) == 0 {
			z.MaxScalingFreq = 0
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *CPUMetrics) Msgsize() (s int) {
	s = 3 + 10 + msgp.TimeSize + 6 + msgp.IntSize + 10
	if z.TimesStat == nil {
		s += msgp.NilSize
	} else {
		s += (*cpuTimesStat)(z.TimesStat).Msgsize()
	}
	s += 9
	if z.LoadStat == nil {
		s += msgp.NilSize
	} else {
		s += (*loadAvgStat)(z.LoadStat).Msgsize()
	}
	s += 9 + msgp.IntSize + 13 + msgp.MapHeaderSize
	if z.CPUByModel != nil {
		for za0001, za0002 := range z.CPUByModel {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + msgp.IntSize
		}
	}
	s += 10 + msgp.Float64Size + 12 + msgp.IntSize + 17 + msgp.Int64Size + 17 + msgp.IntSize + 14 + msgp.MapHeaderSize
	if z.GovernorFreq != nil {
		for za0003, za0004 := range z.GovernorFreq {
			_ = za0004
			s += msgp.StringPrefixSize + len(za0003) + msgp.IntSize
		}
	}
	s += 19 + msgp.Uint64Size + 27 + msgp.Uint64Size + 9 + msgp.Uint64Size + 9 + msgp.Uint64Size + 17 + msgp.Uint64Size + 17 + msgp.Uint64Size
	return
}
