// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package madmin

import (
	"time"

	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *ReplicationMetrics) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 2 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "collected":
			z.CollectedAt, err = dc.ReadTimeUTC()
			if err != nil {
				err = msgp.WrapError(err, "CollectedAt")
				return
			}
		case "nodes":
			z.Nodes, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Nodes")
				return
			}
		case "active":
			z.Active, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Active")
				return
			}
			zb0001Mask |= 0x1
		case "queued":
			z.Queued, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Queued")
				return
			}
			zb0001Mask |= 0x2
		case "targets":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Targets")
				return
			}
			if z.Targets == nil {
				z.Targets = make(map[string]ReplicationTargetStats, zb0002)
			} else if len(z.Targets) > 0 {
				clear(z.Targets)
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Targets")
					return
				}
				var za0002 ReplicationTargetStats
				err = za0002.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Targets", za0001)
					return
				}
				z.Targets[za0001] = za0002
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0x3 {
		if (zb0001Mask & 0x1) == 0 {
			z.Active = 0
		}
		if (zb0001Mask & 0x2) == 0 {
			z.Queued = 0
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ReplicationMetrics) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(5)
	var zb0001Mask uint8 /* 5 bits */
	_ = zb0001Mask
	if z.Active == 0 {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.Queued == 0 {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "collected"
		err = en.Append(0xa9, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64)
		if err != nil {
			return
		}
		err = en.WriteTime(z.CollectedAt)
		if err != nil {
			err = msgp.WrapError(err, "CollectedAt")
			return
		}
		// write "nodes"
		err = en.Append(0xa5, 0x6e, 0x6f, 0x64, 0x65, 0x73)
		if err != nil {
			return
		}
		err = en.WriteInt(z.Nodes)
		if err != nil {
			err = msgp.WrapError(err, "Nodes")
			return
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "active"
			err = en.Append(0xa6, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.Active)
			if err != nil {
				err = msgp.WrapError(err, "Active")
				return
			}
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// write "queued"
			err = en.Append(0xa6, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.Queued)
			if err != nil {
				err = msgp.WrapError(err, "Queued")
				return
			}
		}
		// write "targets"
		err = en.Append(0xa7, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73)
		if err != nil {
			return
		}
		err = en.WriteMapHeader(uint32(len(z.Targets)))
		if err != nil {
			err = msgp.WrapError(err, "Targets")
			return
		}
		for za0001, za0002 := range z.Targets {
			err = en.WriteString(za0001)
			if err != nil {
				err = msgp.WrapError(err, "Targets")
				return
			}
			err = za0002.EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "Targets", za0001)
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ReplicationMetrics) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(5)
	var zb0001Mask uint8 /* 5 bits */
	_ = zb0001Mask
	if z.Active == 0 {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.Queued == 0 {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// string "collected"
		o = append(o, 0xa9, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64)
		o = msgp.AppendTime(o, z.CollectedAt)
		// string "nodes"
		o = append(o, 0xa5, 0x6e, 0x6f, 0x64, 0x65, 0x73)
		o = msgp.AppendInt(o, z.Nodes)
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "active"
			o = append(o, 0xa6, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65)
			o = msgp.AppendInt64(o, z.Active)
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// string "queued"
			o = append(o, 0xa6, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64)
			o = msgp.AppendInt64(o, z.Queued)
		}
		// string "targets"
		o = append(o, 0xa7, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73)
		o = msgp.AppendMapHeader(o, uint32(len(z.Targets)))
		for za0001, za0002 := range z.Targets {
			o = msgp.AppendString(o, za0001)
			o, err = za0002.MarshalMsg(o)
			if err != nil {
				err = msgp.WrapError(err, "Targets", za0001)
				return
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ReplicationMetrics) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 2 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "collected":
			z.CollectedAt, bts, err = msgp.ReadTimeUTCBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CollectedAt")
				return
			}
		case "nodes":
			z.Nodes, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Nodes")
				return
			}
		case "active":
			z.Active, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Active")
				return
			}
			zb0001Mask |= 0x1
		case "queued":
			z.Queued, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Queued")
				return
			}
			zb0001Mask |= 0x2
		case "targets":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Targets")
				return
			}
			if z.Targets == nil {
				z.Targets = make(map[string]ReplicationTargetStats, zb0002)
			} else if len(z.Targets) > 0 {
				clear(z.Targets)
			}
			for zb0002 > 0 {
				var za0002 ReplicationTargetStats
				zb0002--
				var za0001 string
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Targets")
					return
				}
				bts, err = za0002.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Targets", za0001)
					return
				}
				z.Targets[za0001] = za0002
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0x3 {
		if (zb0001Mask & 0x1) == 0 {
			z.Active = 0
		}
		if (zb0001Mask & 0x2) == 0 {
			z.Queued = 0
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ReplicationMetrics) Msgsize() (s int) {
	s = 1 + 10 + msgp.TimeSize + 6 + msgp.IntSize + 7 + msgp.Int64Size + 7 + msgp.Int64Size + 8 + msgp.MapHeaderSize
	if z.Targets != nil {
		for za0001, za0002 := range z.Targets {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + za0002.Msgsize()
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ReplicationStats) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint32 /* 28 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "nodes":
			z.Nodes, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Nodes")
				return
			}
			zb0001Mask |= 0x1
		case "startTime":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "StartTime")
					return
				}
				z.StartTime = nil
			} else {
				if z.StartTime == nil {
					z.StartTime = new(time.Time)
				}
				*z.StartTime, err = dc.ReadTimeUTC()
				if err != nil {
					err = msgp.WrapError(err, "StartTime")
					return
				}
			}
			zb0001Mask |= 0x2
		case "endTime":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "EndTime")
					return
				}
				z.EndTime = nil
			} else {
				if z.EndTime == nil {
					z.EndTime = new(time.Time)
				}
				*z.EndTime, err = dc.ReadTimeUTC()
				if err != nil {
					err = msgp.WrapError(err, "EndTime")
					return
				}
			}
			zb0001Mask |= 0x4
		case "wallTimeSecs":
			z.WallTimeSecs, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "WallTimeSecs")
				return
			}
			zb0001Mask |= 0x8
		case "events":
			z.Events, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Events")
				return
			}
			zb0001Mask |= 0x10
		case "bytes":
			z.Bytes, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Bytes")
				return
			}
			zb0001Mask |= 0x20
		case "timeSecs":
			z.EventTimeSecs, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "EventTimeSecs")
				return
			}
			zb0001Mask |= 0x40
		case "latency":
			z.LatencySecs, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "LatencySecs")
				return
			}
			zb0001Mask |= 0x80
		case "maxLatency":
			z.MaxLatencySecs, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "MaxLatencySecs")
				return
			}
			zb0001Mask |= 0x100
		case "put":
			z.PutObject, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "PutObject")
				return
			}
			zb0001Mask |= 0x200
		case "updateMeta":
			z.UpdateMeta, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "UpdateMeta")
				return
			}
			zb0001Mask |= 0x400
		case "del":
			z.DelObject, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "DelObject")
				return
			}
			zb0001Mask |= 0x800
		case "delTag":
			z.DelTag, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "DelTag")
				return
			}
			zb0001Mask |= 0x1000
		case "putErrs":
			z.PutErrors, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "PutErrors")
				return
			}
			zb0001Mask |= 0x2000
		case "putTagErrs":
			z.UpdateMetaErrors, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "UpdateMetaErrors")
				return
			}
			zb0001Mask |= 0x4000
		case "delErrs":
			z.DelErrors, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "DelErrors")
				return
			}
			zb0001Mask |= 0x8000
		case "delTagErrs":
			z.DelTagErrors, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "DelTagErrors")
				return
			}
			zb0001Mask |= 0x10000
		case "synced":
			z.Synced, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Synced")
				return
			}
			zb0001Mask |= 0x20000
		case "alreadyOK":
			z.AlreadyOK, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "AlreadyOK")
				return
			}
			zb0001Mask |= 0x40000
		case "rejected":
			z.Rejected, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Rejected")
				return
			}
			zb0001Mask |= 0x80000
		case "proxy":
			z.ProxyEvents, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "ProxyEvents")
				return
			}
			zb0001Mask |= 0x100000
		case "proxyBytes":
			z.ProxyBytes, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "ProxyBytes")
				return
			}
			zb0001Mask |= 0x200000
		case "proxyHead":
			z.ProxyHead, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "ProxyHead")
				return
			}
			zb0001Mask |= 0x400000
		case "proxyGet":
			z.ProxyGet, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "ProxyGet")
				return
			}
			zb0001Mask |= 0x800000
		case "proxyGetTag":
			z.ProxyGetTag, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "ProxyGetTag")
				return
			}
			zb0001Mask |= 0x1000000
		case "proxyHeadOK":
			z.ProxyHeadOK, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "ProxyHeadOK")
				return
			}
			zb0001Mask |= 0x2000000
		case "proxyGetOK":
			z.ProxyGetOK, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "ProxyGetOK")
				return
			}
			zb0001Mask |= 0x4000000
		case "proxyGetTagOK":
			z.ProxyGetTagOK, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "ProxyGetTagOK")
				return
			}
			zb0001Mask |= 0x8000000
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0xfffffff {
		if (zb0001Mask & 0x1) == 0 {
			z.Nodes = 0
		}
		if (zb0001Mask & 0x2) == 0 {
			z.StartTime = nil
		}
		if (zb0001Mask & 0x4) == 0 {
			z.EndTime = nil
		}
		if (zb0001Mask & 0x8) == 0 {
			z.WallTimeSecs = 0
		}
		if (zb0001Mask & 0x10) == 0 {
			z.Events = 0
		}
		if (zb0001Mask & 0x20) == 0 {
			z.Bytes = 0
		}
		if (zb0001Mask & 0x40) == 0 {
			z.EventTimeSecs = 0
		}
		if (zb0001Mask & 0x80) == 0 {
			z.LatencySecs = 0
		}
		if (zb0001Mask & 0x100) == 0 {
			z.MaxLatencySecs = 0
		}
		if (zb0001Mask & 0x200) == 0 {
			z.PutObject = 0
		}
		if (zb0001Mask & 0x400) == 0 {
			z.UpdateMeta = 0
		}
		if (zb0001Mask & 0x800) == 0 {
			z.DelObject = 0
		}
		if (zb0001Mask & 0x1000) == 0 {
			z.DelTag = 0
		}
		if (zb0001Mask & 0x2000) == 0 {
			z.PutErrors = 0
		}
		if (zb0001Mask & 0x4000) == 0 {
			z.UpdateMetaErrors = 0
		}
		if (zb0001Mask & 0x8000) == 0 {
			z.DelErrors = 0
		}
		if (zb0001Mask & 0x10000) == 0 {
			z.DelTagErrors = 0
		}
		if (zb0001Mask & 0x20000) == 0 {
			z.Synced = 0
		}
		if (zb0001Mask & 0x40000) == 0 {
			z.AlreadyOK = 0
		}
		if (zb0001Mask & 0x80000) == 0 {
			z.Rejected = 0
		}
		if (zb0001Mask & 0x100000) == 0 {
			z.ProxyEvents = 0
		}
		if (zb0001Mask & 0x200000) == 0 {
			z.ProxyBytes = 0
		}
		if (zb0001Mask & 0x400000) == 0 {
			z.ProxyHead = 0
		}
		if (zb0001Mask & 0x800000) == 0 {
			z.ProxyGet = 0
		}
		if (zb0001Mask & 0x1000000) == 0 {
			z.ProxyGetTag = 0
		}
		if (zb0001Mask & 0x2000000) == 0 {
			z.ProxyHeadOK = 0
		}
		if (zb0001Mask & 0x4000000) == 0 {
			z.ProxyGetOK = 0
		}
		if (zb0001Mask & 0x8000000) == 0 {
			z.ProxyGetTagOK = 0
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ReplicationStats) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(28)
	var zb0001Mask uint32 /* 28 bits */
	_ = zb0001Mask
	if z.Nodes == 0 {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.StartTime == nil {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.EndTime == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.WallTimeSecs == 0 {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.Events == 0 {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.Bytes == 0 {
		zb0001Len--
		zb0001Mask |= 0x20
	}
	if z.EventTimeSecs == 0 {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	if z.LatencySecs == 0 {
		zb0001Len--
		zb0001Mask |= 0x80
	}
	if z.MaxLatencySecs == 0 {
		zb0001Len--
		zb0001Mask |= 0x100
	}
	if z.PutObject == 0 {
		zb0001Len--
		zb0001Mask |= 0x200
	}
	if z.UpdateMeta == 0 {
		zb0001Len--
		zb0001Mask |= 0x400
	}
	if z.DelObject == 0 {
		zb0001Len--
		zb0001Mask |= 0x800
	}
	if z.DelTag == 0 {
		zb0001Len--
		zb0001Mask |= 0x1000
	}
	if z.PutErrors == 0 {
		zb0001Len--
		zb0001Mask |= 0x2000
	}
	if z.UpdateMetaErrors == 0 {
		zb0001Len--
		zb0001Mask |= 0x4000
	}
	if z.DelErrors == 0 {
		zb0001Len--
		zb0001Mask |= 0x8000
	}
	if z.DelTagErrors == 0 {
		zb0001Len--
		zb0001Mask |= 0x10000
	}
	if z.Synced == 0 {
		zb0001Len--
		zb0001Mask |= 0x20000
	}
	if z.AlreadyOK == 0 {
		zb0001Len--
		zb0001Mask |= 0x40000
	}
	if z.Rejected == 0 {
		zb0001Len--
		zb0001Mask |= 0x80000
	}
	if z.ProxyEvents == 0 {
		zb0001Len--
		zb0001Mask |= 0x100000
	}
	if z.ProxyBytes == 0 {
		zb0001Len--
		zb0001Mask |= 0x200000
	}
	if z.ProxyHead == 0 {
		zb0001Len--
		zb0001Mask |= 0x400000
	}
	if z.ProxyGet == 0 {
		zb0001Len--
		zb0001Mask |= 0x800000
	}
	if z.ProxyGetTag == 0 {
		zb0001Len--
		zb0001Mask |= 0x1000000
	}
	if z.ProxyHeadOK == 0 {
		zb0001Len--
		zb0001Mask |= 0x2000000
	}
	if z.ProxyGetOK == 0 {
		zb0001Len--
		zb0001Mask |= 0x4000000
	}
	if z.ProxyGetTagOK == 0 {
		zb0001Len--
		zb0001Mask |= 0x8000000
	}
	// variable map header, size zb0001Len
	err = en.WriteMapHeader(zb0001Len)
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		if (zb0001Mask & 0x1) == 0 { // if not omitted
			// write "nodes"
			err = en.Append(0xa5, 0x6e, 0x6f, 0x64, 0x65, 0x73)
			if err != nil {
				return
			}
			err = en.WriteInt(z.Nodes)
			if err != nil {
				err = msgp.WrapError(err, "Nodes")
				return
			}
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// write "startTime"
			err = en.Append(0xa9, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65)
			if err != nil {
				return
			}
			if z.StartTime == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = en.WriteTime(*z.StartTime)
				if err != nil {
					err = msgp.WrapError(err, "StartTime")
					return
				}
			}
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "endTime"
			err = en.Append(0xa7, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65)
			if err != nil {
				return
			}
			if z.EndTime == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = en.WriteTime(*z.EndTime)
				if err != nil {
					err = msgp.WrapError(err, "EndTime")
					return
				}
			}
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// write "wallTimeSecs"
			err = en.Append(0xac, 0x77, 0x61, 0x6c, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x63, 0x73)
			if err != nil {
				return
			}
			err = en.WriteFloat64(z.WallTimeSecs)
			if err != nil {
				err = msgp.WrapError(err, "WallTimeSecs")
				return
			}
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// write "events"
			err = en.Append(0xa6, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.Events)
			if err != nil {
				err = msgp.WrapError(err, "Events")
				return
			}
		}
		if (zb0001Mask & 0x20) == 0 { // if not omitted
			// write "bytes"
			err = en.Append(0xa5, 0x62, 0x79, 0x74, 0x65, 0x73)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.Bytes)
			if err != nil {
				err = msgp.WrapError(err, "Bytes")
				return
			}
		}
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// write "timeSecs"
			err = en.Append(0xa8, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x63, 0x73)
			if err != nil {
				return
			}
			err = en.WriteFloat64(z.EventTimeSecs)
			if err != nil {
				err = msgp.WrapError(err, "EventTimeSecs")
				return
			}
		}
		if (zb0001Mask & 0x80) == 0 { // if not omitted
			// write "latency"
			err = en.Append(0xa7, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79)
			if err != nil {
				return
			}
			err = en.WriteFloat64(z.LatencySecs)
			if err != nil {
				err = msgp.WrapError(err, "LatencySecs")
				return
			}
		}
		if (zb0001Mask & 0x100) == 0 { // if not omitted
			// write "maxLatency"
			err = en.Append(0xaa, 0x6d, 0x61, 0x78, 0x4c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79)
			if err != nil {
				return
			}
			err = en.WriteFloat64(z.MaxLatencySecs)
			if err != nil {
				err = msgp.WrapError(err, "MaxLatencySecs")
				return
			}
		}
		if (zb0001Mask & 0x200) == 0 { // if not omitted
			// write "put"
			err = en.Append(0xa3, 0x70, 0x75, 0x74)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.PutObject)
			if err != nil {
				err = msgp.WrapError(err, "PutObject")
				return
			}
		}
		if (zb0001Mask & 0x400) == 0 { // if not omitted
			// write "updateMeta"
			err = en.Append(0xaa, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x61)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.UpdateMeta)
			if err != nil {
				err = msgp.WrapError(err, "UpdateMeta")
				return
			}
		}
		if (zb0001Mask & 0x800) == 0 { // if not omitted
			// write "del"
			err = en.Append(0xa3, 0x64, 0x65, 0x6c)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.DelObject)
			if err != nil {
				err = msgp.WrapError(err, "DelObject")
				return
			}
		}
		if (zb0001Mask & 0x1000) == 0 { // if not omitted
			// write "delTag"
			err = en.Append(0xa6, 0x64, 0x65, 0x6c, 0x54, 0x61, 0x67)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.DelTag)
			if err != nil {
				err = msgp.WrapError(err, "DelTag")
				return
			}
		}
		if (zb0001Mask & 0x2000) == 0 { // if not omitted
			// write "putErrs"
			err = en.Append(0xa7, 0x70, 0x75, 0x74, 0x45, 0x72, 0x72, 0x73)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.PutErrors)
			if err != nil {
				err = msgp.WrapError(err, "PutErrors")
				return
			}
		}
		if (zb0001Mask & 0x4000) == 0 { // if not omitted
			// write "putTagErrs"
			err = en.Append(0xaa, 0x70, 0x75, 0x74, 0x54, 0x61, 0x67, 0x45, 0x72, 0x72, 0x73)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.UpdateMetaErrors)
			if err != nil {
				err = msgp.WrapError(err, "UpdateMetaErrors")
				return
			}
		}
		if (zb0001Mask & 0x8000) == 0 { // if not omitted
			// write "delErrs"
			err = en.Append(0xa7, 0x64, 0x65, 0x6c, 0x45, 0x72, 0x72, 0x73)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.DelErrors)
			if err != nil {
				err = msgp.WrapError(err, "DelErrors")
				return
			}
		}
		if (zb0001Mask & 0x10000) == 0 { // if not omitted
			// write "delTagErrs"
			err = en.Append(0xaa, 0x64, 0x65, 0x6c, 0x54, 0x61, 0x67, 0x45, 0x72, 0x72, 0x73)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.DelTagErrors)
			if err != nil {
				err = msgp.WrapError(err, "DelTagErrors")
				return
			}
		}
		if (zb0001Mask & 0x20000) == 0 { // if not omitted
			// write "synced"
			err = en.Append(0xa6, 0x73, 0x79, 0x6e, 0x63, 0x65, 0x64)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.Synced)
			if err != nil {
				err = msgp.WrapError(err, "Synced")
				return
			}
		}
		if (zb0001Mask & 0x40000) == 0 { // if not omitted
			// write "alreadyOK"
			err = en.Append(0xa9, 0x61, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x4f, 0x4b)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.AlreadyOK)
			if err != nil {
				err = msgp.WrapError(err, "AlreadyOK")
				return
			}
		}
		if (zb0001Mask & 0x80000) == 0 { // if not omitted
			// write "rejected"
			err = en.Append(0xa8, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.Rejected)
			if err != nil {
				err = msgp.WrapError(err, "Rejected")
				return
			}
		}
		if (zb0001Mask & 0x100000) == 0 { // if not omitted
			// write "proxy"
			err = en.Append(0xa5, 0x70, 0x72, 0x6f, 0x78, 0x79)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.ProxyEvents)
			if err != nil {
				err = msgp.WrapError(err, "ProxyEvents")
				return
			}
		}
		if (zb0001Mask & 0x200000) == 0 { // if not omitted
			// write "proxyBytes"
			err = en.Append(0xaa, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x42, 0x79, 0x74, 0x65, 0x73)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.ProxyBytes)
			if err != nil {
				err = msgp.WrapError(err, "ProxyBytes")
				return
			}
		}
		if (zb0001Mask & 0x400000) == 0 { // if not omitted
			// write "proxyHead"
			err = en.Append(0xa9, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x48, 0x65, 0x61, 0x64)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.ProxyHead)
			if err != nil {
				err = msgp.WrapError(err, "ProxyHead")
				return
			}
		}
		if (zb0001Mask & 0x800000) == 0 { // if not omitted
			// write "proxyGet"
			err = en.Append(0xa8, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x47, 0x65, 0x74)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.ProxyGet)
			if err != nil {
				err = msgp.WrapError(err, "ProxyGet")
				return
			}
		}
		if (zb0001Mask & 0x1000000) == 0 { // if not omitted
			// write "proxyGetTag"
			err = en.Append(0xab, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.ProxyGetTag)
			if err != nil {
				err = msgp.WrapError(err, "ProxyGetTag")
				return
			}
		}
		if (zb0001Mask & 0x2000000) == 0 { // if not omitted
			// write "proxyHeadOK"
			err = en.Append(0xab, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x48, 0x65, 0x61, 0x64, 0x4f, 0x4b)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.ProxyHeadOK)
			if err != nil {
				err = msgp.WrapError(err, "ProxyHeadOK")
				return
			}
		}
		if (zb0001Mask & 0x4000000) == 0 { // if not omitted
			// write "proxyGetOK"
			err = en.Append(0xaa, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x47, 0x65, 0x74, 0x4f, 0x4b)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.ProxyGetOK)
			if err != nil {
				err = msgp.WrapError(err, "ProxyGetOK")
				return
			}
		}
		if (zb0001Mask & 0x8000000) == 0 { // if not omitted
			// write "proxyGetTagOK"
			err = en.Append(0xad, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x4f, 0x4b)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.ProxyGetTagOK)
			if err != nil {
				err = msgp.WrapError(err, "ProxyGetTagOK")
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ReplicationStats) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(28)
	var zb0001Mask uint32 /* 28 bits */
	_ = zb0001Mask
	if z.Nodes == 0 {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.StartTime == nil {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.EndTime == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.WallTimeSecs == 0 {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.Events == 0 {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.Bytes == 0 {
		zb0001Len--
		zb0001Mask |= 0x20
	}
	if z.EventTimeSecs == 0 {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	if z.LatencySecs == 0 {
		zb0001Len--
		zb0001Mask |= 0x80
	}
	if z.MaxLatencySecs == 0 {
		zb0001Len--
		zb0001Mask |= 0x100
	}
	if z.PutObject == 0 {
		zb0001Len--
		zb0001Mask |= 0x200
	}
	if z.UpdateMeta == 0 {
		zb0001Len--
		zb0001Mask |= 0x400
	}
	if z.DelObject == 0 {
		zb0001Len--
		zb0001Mask |= 0x800
	}
	if z.DelTag == 0 {
		zb0001Len--
		zb0001Mask |= 0x1000
	}
	if z.PutErrors == 0 {
		zb0001Len--
		zb0001Mask |= 0x2000
	}
	if z.UpdateMetaErrors == 0 {
		zb0001Len--
		zb0001Mask |= 0x4000
	}
	if z.DelErrors == 0 {
		zb0001Len--
		zb0001Mask |= 0x8000
	}
	if z.DelTagErrors == 0 {
		zb0001Len--
		zb0001Mask |= 0x10000
	}
	if z.Synced == 0 {
		zb0001Len--
		zb0001Mask |= 0x20000
	}
	if z.AlreadyOK == 0 {
		zb0001Len--
		zb0001Mask |= 0x40000
	}
	if z.Rejected == 0 {
		zb0001Len--
		zb0001Mask |= 0x80000
	}
	if z.ProxyEvents == 0 {
		zb0001Len--
		zb0001Mask |= 0x100000
	}
	if z.ProxyBytes == 0 {
		zb0001Len--
		zb0001Mask |= 0x200000
	}
	if z.ProxyHead == 0 {
		zb0001Len--
		zb0001Mask |= 0x400000
	}
	if z.ProxyGet == 0 {
		zb0001Len--
		zb0001Mask |= 0x800000
	}
	if z.ProxyGetTag == 0 {
		zb0001Len--
		zb0001Mask |= 0x1000000
	}
	if z.ProxyHeadOK == 0 {
		zb0001Len--
		zb0001Mask |= 0x2000000
	}
	if z.ProxyGetOK == 0 {
		zb0001Len--
		zb0001Mask |= 0x4000000
	}
	if z.ProxyGetTagOK == 0 {
		zb0001Len--
		zb0001Mask |= 0x8000000
	}
	// variable map header, size zb0001Len
	o = msgp.AppendMapHeader(o, zb0001Len)

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		if (zb0001Mask & 0x1) == 0 { // if not omitted
			// string "nodes"
			o = append(o, 0xa5, 0x6e, 0x6f, 0x64, 0x65, 0x73)
			o = msgp.AppendInt(o, z.Nodes)
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// string "startTime"
			o = append(o, 0xa9, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65)
			if z.StartTime == nil {
				o = msgp.AppendNil(o)
			} else {
				o = msgp.AppendTime(o, *z.StartTime)
			}
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "endTime"
			o = append(o, 0xa7, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65)
			if z.EndTime == nil {
				o = msgp.AppendNil(o)
			} else {
				o = msgp.AppendTime(o, *z.EndTime)
			}
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// string "wallTimeSecs"
			o = append(o, 0xac, 0x77, 0x61, 0x6c, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x63, 0x73)
			o = msgp.AppendFloat64(o, z.WallTimeSecs)
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// string "events"
			o = append(o, 0xa6, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73)
			o = msgp.AppendInt64(o, z.Events)
		}
		if (zb0001Mask & 0x20) == 0 { // if not omitted
			// string "bytes"
			o = append(o, 0xa5, 0x62, 0x79, 0x74, 0x65, 0x73)
			o = msgp.AppendInt64(o, z.Bytes)
		}
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// string "timeSecs"
			o = append(o, 0xa8, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x63, 0x73)
			o = msgp.AppendFloat64(o, z.EventTimeSecs)
		}
		if (zb0001Mask & 0x80) == 0 { // if not omitted
			// string "latency"
			o = append(o, 0xa7, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79)
			o = msgp.AppendFloat64(o, z.LatencySecs)
		}
		if (zb0001Mask & 0x100) == 0 { // if not omitted
			// string "maxLatency"
			o = append(o, 0xaa, 0x6d, 0x61, 0x78, 0x4c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79)
			o = msgp.AppendFloat64(o, z.MaxLatencySecs)
		}
		if (zb0001Mask & 0x200) == 0 { // if not omitted
			// string "put"
			o = append(o, 0xa3, 0x70, 0x75, 0x74)
			o = msgp.AppendInt64(o, z.PutObject)
		}
		if (zb0001Mask & 0x400) == 0 { // if not omitted
			// string "updateMeta"
			o = append(o, 0xaa, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x61)
			o = msgp.AppendInt64(o, z.UpdateMeta)
		}
		if (zb0001Mask & 0x800) == 0 { // if not omitted
			// string "del"
			o = append(o, 0xa3, 0x64, 0x65, 0x6c)
			o = msgp.AppendInt64(o, z.DelObject)
		}
		if (zb0001Mask & 0x1000) == 0 { // if not omitted
			// string "delTag"
			o = append(o, 0xa6, 0x64, 0x65, 0x6c, 0x54, 0x61, 0x67)
			o = msgp.AppendInt64(o, z.DelTag)
		}
		if (zb0001Mask & 0x2000) == 0 { // if not omitted
			// string "putErrs"
			o = append(o, 0xa7, 0x70, 0x75, 0x74, 0x45, 0x72, 0x72, 0x73)
			o = msgp.AppendInt64(o, z.PutErrors)
		}
		if (zb0001Mask & 0x4000) == 0 { // if not omitted
			// string "putTagErrs"
			o = append(o, 0xaa, 0x70, 0x75, 0x74, 0x54, 0x61, 0x67, 0x45, 0x72, 0x72, 0x73)
			o = msgp.AppendInt64(o, z.UpdateMetaErrors)
		}
		if (zb0001Mask & 0x8000) == 0 { // if not omitted
			// string "delErrs"
			o = append(o, 0xa7, 0x64, 0x65, 0x6c, 0x45, 0x72, 0x72, 0x73)
			o = msgp.AppendInt64(o, z.DelErrors)
		}
		if (zb0001Mask & 0x10000) == 0 { // if not omitted
			// string "delTagErrs"
			o = append(o, 0xaa, 0x64, 0x65, 0x6c, 0x54, 0x61, 0x67, 0x45, 0x72, 0x72, 0x73)
			o = msgp.AppendInt64(o, z.DelTagErrors)
		}
		if (zb0001Mask & 0x20000) == 0 { // if not omitted
			// string "synced"
			o = append(o, 0xa6, 0x73, 0x79, 0x6e, 0x63, 0x65, 0x64)
			o = msgp.AppendInt64(o, z.Synced)
		}
		if (zb0001Mask & 0x40000) == 0 { // if not omitted
			// string "alreadyOK"
			o = append(o, 0xa9, 0x61, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x4f, 0x4b)
			o = msgp.AppendInt64(o, z.AlreadyOK)
		}
		if (zb0001Mask & 0x80000) == 0 { // if not omitted
			// string "rejected"
			o = append(o, 0xa8, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64)
			o = msgp.AppendInt64(o, z.Rejected)
		}
		if (zb0001Mask & 0x100000) == 0 { // if not omitted
			// string "proxy"
			o = append(o, 0xa5, 0x70, 0x72, 0x6f, 0x78, 0x79)
			o = msgp.AppendInt64(o, z.ProxyEvents)
		}
		if (zb0001Mask & 0x200000) == 0 { // if not omitted
			// string "proxyBytes"
			o = append(o, 0xaa, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x42, 0x79, 0x74, 0x65, 0x73)
			o = msgp.AppendInt64(o, z.ProxyBytes)
		}
		if (zb0001Mask & 0x400000) == 0 { // if not omitted
			// string "proxyHead"
			o = append(o, 0xa9, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x48, 0x65, 0x61, 0x64)
			o = msgp.AppendInt64(o, z.ProxyHead)
		}
		if (zb0001Mask & 0x800000) == 0 { // if not omitted
			// string "proxyGet"
			o = append(o, 0xa8, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x47, 0x65, 0x74)
			o = msgp.AppendInt64(o, z.ProxyGet)
		}
		if (zb0001Mask & 0x1000000) == 0 { // if not omitted
			// string "proxyGetTag"
			o = append(o, 0xab, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67)
			o = msgp.AppendInt64(o, z.ProxyGetTag)
		}
		if (zb0001Mask & 0x2000000) == 0 { // if not omitted
			// string "proxyHeadOK"
			o = append(o, 0xab, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x48, 0x65, 0x61, 0x64, 0x4f, 0x4b)
			o = msgp.AppendInt64(o, z.ProxyHeadOK)
		}
		if (zb0001Mask & 0x4000000) == 0 { // if not omitted
			// string "proxyGetOK"
			o = append(o, 0xaa, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x47, 0x65, 0x74, 0x4f, 0x4b)
			o = msgp.AppendInt64(o, z.ProxyGetOK)
		}
		if (zb0001Mask & 0x8000000) == 0 { // if not omitted
			// string "proxyGetTagOK"
			o = append(o, 0xad, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x4f, 0x4b)
			o = msgp.AppendInt64(o, z.ProxyGetTagOK)
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ReplicationStats) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint32 /* 28 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "nodes":
			z.Nodes, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Nodes")
				return
			}
			zb0001Mask |= 0x1
		case "startTime":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.StartTime = nil
			} else {
				if z.StartTime == nil {
					z.StartTime = new(time.Time)
				}
				*z.StartTime, bts, err = msgp.ReadTimeUTCBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "StartTime")
					return
				}
			}
			zb0001Mask |= 0x2
		case "endTime":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.EndTime = nil
			} else {
				if z.EndTime == nil {
					z.EndTime = new(time.Time)
				}
				*z.EndTime, bts, err = msgp.ReadTimeUTCBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "EndTime")
					return
				}
			}
			zb0001Mask |= 0x4
		case "wallTimeSecs":
			z.WallTimeSecs, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "WallTimeSecs")
				return
			}
			zb0001Mask |= 0x8
		case "events":
			z.Events, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Events")
				return
			}
			zb0001Mask |= 0x10
		case "bytes":
			z.Bytes, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Bytes")
				return
			}
			zb0001Mask |= 0x20
		case "timeSecs":
			z.EventTimeSecs, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "EventTimeSecs")
				return
			}
			zb0001Mask |= 0x40
		case "latency":
			z.LatencySecs, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LatencySecs")
				return
			}
			zb0001Mask |= 0x80
		case "maxLatency":
			z.MaxLatencySecs, bts, err = msgp.ReadFloat64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "MaxLatencySecs")
				return
			}
			zb0001Mask |= 0x100
		case "put":
			z.PutObject, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PutObject")
				return
			}
			zb0001Mask |= 0x200
		case "updateMeta":
			z.UpdateMeta, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UpdateMeta")
				return
			}
			zb0001Mask |= 0x400
		case "del":
			z.DelObject, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DelObject")
				return
			}
			zb0001Mask |= 0x800
		case "delTag":
			z.DelTag, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DelTag")
				return
			}
			zb0001Mask |= 0x1000
		case "putErrs":
			z.PutErrors, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PutErrors")
				return
			}
			zb0001Mask |= 0x2000
		case "putTagErrs":
			z.UpdateMetaErrors, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UpdateMetaErrors")
				return
			}
			zb0001Mask |= 0x4000
		case "delErrs":
			z.DelErrors, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DelErrors")
				return
			}
			zb0001Mask |= 0x8000
		case "delTagErrs":
			z.DelTagErrors, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DelTagErrors")
				return
			}
			zb0001Mask |= 0x10000
		case "synced":
			z.Synced, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Synced")
				return
			}
			zb0001Mask |= 0x20000
		case "alreadyOK":
			z.AlreadyOK, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "AlreadyOK")
				return
			}
			zb0001Mask |= 0x40000
		case "rejected":
			z.Rejected, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Rejected")
				return
			}
			zb0001Mask |= 0x80000
		case "proxy":
			z.ProxyEvents, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ProxyEvents")
				return
			}
			zb0001Mask |= 0x100000
		case "proxyBytes":
			z.ProxyBytes, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ProxyBytes")
				return
			}
			zb0001Mask |= 0x200000
		case "proxyHead":
			z.ProxyHead, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ProxyHead")
				return
			}
			zb0001Mask |= 0x400000
		case "proxyGet":
			z.ProxyGet, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ProxyGet")
				return
			}
			zb0001Mask |= 0x800000
		case "proxyGetTag":
			z.ProxyGetTag, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ProxyGetTag")
				return
			}
			zb0001Mask |= 0x1000000
		case "proxyHeadOK":
			z.ProxyHeadOK, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ProxyHeadOK")
				return
			}
			zb0001Mask |= 0x2000000
		case "proxyGetOK":
			z.ProxyGetOK, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ProxyGetOK")
				return
			}
			zb0001Mask |= 0x4000000
		case "proxyGetTagOK":
			z.ProxyGetTagOK, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ProxyGetTagOK")
				return
			}
			zb0001Mask |= 0x8000000
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0xfffffff {
		if (zb0001Mask & 0x1) == 0 {
			z.Nodes = 0
		}
		if (zb0001Mask & 0x2) == 0 {
			z.StartTime = nil
		}
		if (zb0001Mask & 0x4) == 0 {
			z.EndTime = nil
		}
		if (zb0001Mask & 0x8) == 0 {
			z.WallTimeSecs = 0
		}
		if (zb0001Mask & 0x10) == 0 {
			z.Events = 0
		}
		if (zb0001Mask & 0x20) == 0 {
			z.Bytes = 0
		}
		if (zb0001Mask & 0x40) == 0 {
			z.EventTimeSecs = 0
		}
		if (zb0001Mask & 0x80) == 0 {
			z.LatencySecs = 0
		}
		if (zb0001Mask & 0x100) == 0 {
			z.MaxLatencySecs = 0
		}
		if (zb0001Mask & 0x200) == 0 {
			z.PutObject = 0
		}
		if (zb0001Mask & 0x400) == 0 {
			z.UpdateMeta = 0
		}
		if (zb0001Mask & 0x800) == 0 {
			z.DelObject = 0
		}
		if (zb0001Mask & 0x1000) == 0 {
			z.DelTag = 0
		}
		if (zb0001Mask & 0x2000) == 0 {
			z.PutErrors = 0
		}
		if (zb0001Mask & 0x4000) == 0 {
			z.UpdateMetaErrors = 0
		}
		if (zb0001Mask & 0x8000) == 0 {
			z.DelErrors = 0
		}
		if (zb0001Mask & 0x10000) == 0 {
			z.DelTagErrors = 0
		}
		if (zb0001Mask & 0x20000) == 0 {
			z.Synced = 0
		}
		if (zb0001Mask & 0x40000) == 0 {
			z.AlreadyOK = 0
		}
		if (zb0001Mask & 0x80000) == 0 {
			z.Rejected = 0
		}
		if (zb0001Mask & 0x100000) == 0 {
			z.ProxyEvents = 0
		}
		if (zb0001Mask & 0x200000) == 0 {
			z.ProxyBytes = 0
		}
		if (zb0001Mask & 0x400000) == 0 {
			z.ProxyHead = 0
		}
		if (zb0001Mask & 0x800000) == 0 {
			z.ProxyGet = 0
		}
		if (zb0001Mask & 0x1000000) == 0 {
			z.ProxyGetTag = 0
		}
		if (zb0001Mask & 0x2000000) == 0 {
			z.ProxyHeadOK = 0
		}
		if (zb0001Mask & 0x4000000) == 0 {
			z.ProxyGetOK = 0
		}
		if (zb0001Mask & 0x8000000) == 0 {
			z.ProxyGetTagOK = 0
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ReplicationStats) Msgsize() (s int) {
	s = 3 + 6 + msgp.IntSize + 10
	if z.StartTime == nil {
		s += msgp.NilSize
	} else {
		s += msgp.TimeSize
	}
	s += 8
	if z.EndTime == nil {
		s += msgp.NilSize
	} else {
		s += msgp.TimeSize
	}
	s += 13 + msgp.Float64Size + 7 + msgp.Int64Size + 6 + msgp.Int64Size + 9 + msgp.Float64Size + 8 + msgp.Float64Size + 11 + msgp.Float64Size + 4 + msgp.Int64Size + 11 + msgp.Int64Size + 4 + msgp.Int64Size + 7 + msgp.Int64Size + 8 + msgp.Int64Size + 11 + msgp.Int64Size + 8 + msgp.Int64Size + 11 + msgp.Int64Size + 7 + msgp.Int64Size + 10 + msgp.Int64Size + 9 + msgp.Int64Size + 6 + msgp.Int64Size + 11 + msgp.Int64Size + 10 + msgp.Int64Size + 9 + msgp.Int64Size + 12 + msgp.Int64Size + 12 + msgp.Int64Size + 11 + msgp.Int64Size + 14 + msgp.Int64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ReplicationTargetStats) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 2 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "nodes":
			z.Nodes, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Nodes")
				return
			}
		case "last_hour":
			err = z.LastHour.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "LastHour")
				return
			}
			zb0001Mask |= 0x1
		case "last_day":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "LastDay")
					return
				}
				z.LastDay = nil
			} else {
				if z.LastDay == nil {
					z.LastDay = new(SegmentedReplicationStats)
				}
				err = (*Segmented[ReplicationStats, *ReplicationStats])(z.LastDay).DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "LastDay")
					return
				}
			}
			zb0001Mask |= 0x2
		case "since_start":
			err = z.SinceStart.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "SinceStart")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0x3 {
		if (zb0001Mask & 0x1) == 0 {
			z.LastHour = ReplicationStats{}
		}
		if (zb0001Mask & 0x2) == 0 {
			z.LastDay = nil
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ReplicationTargetStats) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(4)
	var zb0001Mask uint8 /* 4 bits */
	_ = zb0001Mask
	if z.LastDay == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "nodes"
		err = en.Append(0xa5, 0x6e, 0x6f, 0x64, 0x65, 0x73)
		if err != nil {
			return
		}
		err = en.WriteInt(z.Nodes)
		if err != nil {
			err = msgp.WrapError(err, "Nodes")
			return
		}
		// write "last_hour"
		err = en.Append(0xa9, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x68, 0x6f, 0x75, 0x72)
		if err != nil {
			return
		}
		err = z.LastHour.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "LastHour")
			return
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "last_day"
			err = en.Append(0xa8, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x64, 0x61, 0x79)
			if err != nil {
				return
			}
			if z.LastDay == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = (*Segmented[ReplicationStats, *ReplicationStats])(z.LastDay).EncodeMsg(en)
				if err != nil {
					err = msgp.WrapError(err, "LastDay")
					return
				}
			}
		}
		// write "since_start"
		err = en.Append(0xab, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74)
		if err != nil {
			return
		}
		err = z.SinceStart.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "SinceStart")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *ReplicationTargetStats) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(4)
	var zb0001Mask uint8 /* 4 bits */
	_ = zb0001Mask
	if z.LastDay == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// string "nodes"
		o = append(o, 0xa5, 0x6e, 0x6f, 0x64, 0x65, 0x73)
		o = msgp.AppendInt(o, z.Nodes)
		// string "last_hour"
		o = append(o, 0xa9, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x68, 0x6f, 0x75, 0x72)
		o, err = z.LastHour.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "LastHour")
			return
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "last_day"
			o = append(o, 0xa8, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x64, 0x61, 0x79)
			if z.LastDay == nil {
				o = msgp.AppendNil(o)
			} else {
				o, err = (*Segmented[ReplicationStats, *ReplicationStats])(z.LastDay).MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "LastDay")
					return
				}
			}
		}
		// string "since_start"
		o = append(o, 0xab, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74)
		o, err = z.SinceStart.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "SinceStart")
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ReplicationTargetStats) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 2 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "nodes":
			z.Nodes, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Nodes")
				return
			}
		case "last_hour":
			bts, err = z.LastHour.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "LastHour")
				return
			}
			zb0001Mask |= 0x1
		case "last_day":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.LastDay = nil
			} else {
				if z.LastDay == nil {
					z.LastDay = new(SegmentedReplicationStats)
				}
				bts, err = (*Segmented[ReplicationStats, *ReplicationStats])(z.LastDay).UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "LastDay")
					return
				}
			}
			zb0001Mask |= 0x2
		case "since_start":
			bts, err = z.SinceStart.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "SinceStart")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0x3 {
		if (zb0001Mask & 0x1) == 0 {
			z.LastHour = ReplicationStats{}
		}
		if (zb0001Mask & 0x2) == 0 {
			z.LastDay = nil
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ReplicationTargetStats) Msgsize() (s int) {
	s = 1 + 6 + msgp.IntSize + 10 + z.LastHour.Msgsize() + 9
	if z.LastDay == nil {
		s += msgp.NilSize
	} else {
		s += (*Segmented[ReplicationStats, *ReplicationStats])(z.LastDay).Msgsize()
	}
	s += 12 + z.SinceStart.Msgsize()
	return
}
