// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package madmin

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *TraceCallStats) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "inputbytes":
			z.InputBytes, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "InputBytes")
				return
			}
		case "outputbytes":
			z.OutputBytes, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "OutputBytes")
				return
			}
		case "timetofirstbyte":
			z.TimeToFirstByte, err = dc.ReadDuration()
			if err != nil {
				err = msgp.WrapError(err, "TimeToFirstByte")
				return
			}
		case "readBlocked":
			z.ReadBlocked, err = dc.ReadDuration()
			if err != nil {
				err = msgp.WrapError(err, "ReadBlocked")
				return
			}
		case "writeBlocked":
			z.WriteBlocked, err = dc.ReadDuration()
			if err != nil {
				err = msgp.WrapError(err, "WriteBlocked")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *TraceCallStats) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "inputbytes"
	err = en.Append(0x85, 0xaa, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x62, 0x79, 0x74, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt(z.InputBytes)
	if err != nil {
		err = msgp.WrapError(err, "InputBytes")
		return
	}
	// write "outputbytes"
	err = en.Append(0xab, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x62, 0x79, 0x74, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt(z.OutputBytes)
	if err != nil {
		err = msgp.WrapError(err, "OutputBytes")
		return
	}
	// write "timetofirstbyte"
	err = en.Append(0xaf, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x6f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x62, 0x79, 0x74, 0x65)
	if err != nil {
		return
	}
	err = en.WriteDuration(z.TimeToFirstByte)
	if err != nil {
		err = msgp.WrapError(err, "TimeToFirstByte")
		return
	}
	// write "readBlocked"
	err = en.Append(0xab, 0x72, 0x65, 0x61, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64)
	if err != nil {
		return
	}
	err = en.WriteDuration(z.ReadBlocked)
	if err != nil {
		err = msgp.WrapError(err, "ReadBlocked")
		return
	}
	// write "writeBlocked"
	err = en.Append(0xac, 0x77, 0x72, 0x69, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64)
	if err != nil {
		return
	}
	err = en.WriteDuration(z.WriteBlocked)
	if err != nil {
		err = msgp.WrapError(err, "WriteBlocked")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *TraceCallStats) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "inputbytes"
	o = append(o, 0x85, 0xaa, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x62, 0x79, 0x74, 0x65, 0x73)
	o = msgp.AppendInt(o, z.InputBytes)
	// string "outputbytes"
	o = append(o, 0xab, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x62, 0x79, 0x74, 0x65, 0x73)
	o = msgp.AppendInt(o, z.OutputBytes)
	// string "timetofirstbyte"
	o = append(o, 0xaf, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x6f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x62, 0x79, 0x74, 0x65)
	o = msgp.AppendDuration(o, z.TimeToFirstByte)
	// string "readBlocked"
	o = append(o, 0xab, 0x72, 0x65, 0x61, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64)
	o = msgp.AppendDuration(o, z.ReadBlocked)
	// string "writeBlocked"
	o = append(o, 0xac, 0x77, 0x72, 0x69, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64)
	o = msgp.AppendDuration(o, z.WriteBlocked)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *TraceCallStats) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "inputbytes":
			z.InputBytes, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "InputBytes")
				return
			}
		case "outputbytes":
			z.OutputBytes, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "OutputBytes")
				return
			}
		case "timetofirstbyte":
			z.TimeToFirstByte, bts, err = msgp.ReadDurationBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TimeToFirstByte")
				return
			}
		case "readBlocked":
			z.ReadBlocked, bts, err = msgp.ReadDurationBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ReadBlocked")
				return
			}
		case "writeBlocked":
			z.WriteBlocked, bts, err = msgp.ReadDurationBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "WriteBlocked")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *TraceCallStats) Msgsize() (s int) {
	s = 1 + 11 + msgp.IntSize + 12 + msgp.IntSize + 16 + msgp.DurationSize + 12 + msgp.DurationSize + 13 + msgp.DurationSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *TraceHTTPStats) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "request":
			err = z.ReqInfo.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "ReqInfo")
				return
			}
		case "response":
			err = z.RespInfo.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "RespInfo")
				return
			}
		case "stats":
			err = z.CallStats.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "CallStats")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *TraceHTTPStats) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "request"
	err = en.Append(0x83, 0xa7, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74)
	if err != nil {
		return
	}
	err = z.ReqInfo.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "ReqInfo")
		return
	}
	// write "response"
	err = en.Append(0xa8, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65)
	if err != nil {
		return
	}
	err = z.RespInfo.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "RespInfo")
		return
	}
	// write "stats"
	err = en.Append(0xa5, 0x73, 0x74, 0x61, 0x74, 0x73)
	if err != nil {
		return
	}
	err = z.CallStats.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "CallStats")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *TraceHTTPStats) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "request"
	o = append(o, 0x83, 0xa7, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74)
	o, err = z.ReqInfo.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "ReqInfo")
		return
	}
	// string "response"
	o = append(o, 0xa8, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65)
	o, err = z.RespInfo.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "RespInfo")
		return
	}
	// string "stats"
	o = append(o, 0xa5, 0x73, 0x74, 0x61, 0x74, 0x73)
	o, err = z.CallStats.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "CallStats")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *TraceHTTPStats) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "request":
			bts, err = z.ReqInfo.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "ReqInfo")
				return
			}
		case "response":
			bts, err = z.RespInfo.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "RespInfo")
				return
			}
		case "stats":
			bts, err = z.CallStats.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "CallStats")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *TraceHTTPStats) Msgsize() (s int) {
	s = 1 + 8 + z.ReqInfo.Msgsize() + 9 + z.RespInfo.Msgsize() + 6 + z.CallStats.Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *TraceInfo) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 6 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "type":
			{
				var zb0002 uint64
				zb0002, err = dc.ReadUint64()
				if err != nil {
					err = msgp.WrapError(err, "TraceType")
					return
				}
				z.TraceType = TraceType(zb0002)
			}
		case "nodename":
			z.NodeName, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "NodeName")
				return
			}
		case "funcname":
			z.FuncName, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "FuncName")
				return
			}
		case "time":
			z.Time, err = dc.ReadTimeUTC()
			if err != nil {
				err = msgp.WrapError(err, "Time")
				return
			}
		case "path":
			z.Path, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Path")
				return
			}
		case "dur":
			z.Duration, err = dc.ReadDuration()
			if err != nil {
				err = msgp.WrapError(err, "Duration")
				return
			}
		case "bytes":
			z.Bytes, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Bytes")
				return
			}
			zb0001Mask |= 0x1
		case "msg":
			z.Message, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Message")
				return
			}
			zb0001Mask |= 0x2
		case "error":
			z.Error, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Error")
				return
			}
			zb0001Mask |= 0x4
		case "custom":
			var zb0003 uint32
			zb0003, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Custom")
				return
			}
			if z.Custom == nil {
				z.Custom = make(map[string]string, zb0003)
			} else if len(z.Custom) > 0 {
				clear(z.Custom)
			}
			for zb0003 > 0 {
				zb0003--
				var za0001 string
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Custom")
					return
				}
				var za0002 string
				za0002, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Custom", za0001)
					return
				}
				z.Custom[za0001] = za0002
			}
			zb0001Mask |= 0x8
		case "http":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "HTTP")
					return
				}
				z.HTTP = nil
			} else {
				if z.HTTP == nil {
					z.HTTP = new(TraceHTTPStats)
				}
				var zb0004 uint32
				zb0004, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "HTTP")
					return
				}
				for zb0004 > 0 {
					zb0004--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "HTTP")
						return
					}
					switch msgp.UnsafeString(field) {
					case "request":
						err = z.HTTP.ReqInfo.DecodeMsg(dc)
						if err != nil {
							err = msgp.WrapError(err, "HTTP", "ReqInfo")
							return
						}
					case "response":
						err = z.HTTP.RespInfo.DecodeMsg(dc)
						if err != nil {
							err = msgp.WrapError(err, "HTTP", "RespInfo")
							return
						}
					case "stats":
						err = z.HTTP.CallStats.DecodeMsg(dc)
						if err != nil {
							err = msgp.WrapError(err, "HTTP", "CallStats")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "HTTP")
							return
						}
					}
				}
			}
			zb0001Mask |= 0x10
		case "healResult":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "HealResult")
					return
				}
				z.HealResult = nil
			} else {
				if z.HealResult == nil {
					z.HealResult = new(HealResultItem)
				}
				err = z.HealResult.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "HealResult")
					return
				}
			}
			zb0001Mask |= 0x20
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0x3f {
		if (zb0001Mask & 0x1) == 0 {
			z.Bytes = 0
		}
		if (zb0001Mask & 0x2) == 0 {
			z.Message = ""
		}
		if (zb0001Mask & 0x4) == 0 {
			z.Error = ""
		}
		if (zb0001Mask & 0x8) == 0 {
			z.Custom = nil
		}
		if (zb0001Mask & 0x10) == 0 {
			z.HTTP = nil
		}
		if (zb0001Mask & 0x20) == 0 {
			z.HealResult = nil
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *TraceInfo) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(12)
	var zb0001Mask uint16 /* 12 bits */
	_ = zb0001Mask
	if z.Bytes == 0 {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	if z.Message == "" {
		zb0001Len--
		zb0001Mask |= 0x80
	}
	if z.Error == "" {
		zb0001Len--
		zb0001Mask |= 0x100
	}
	if z.Custom == nil {
		zb0001Len--
		zb0001Mask |= 0x200
	}
	if z.HTTP == nil {
		zb0001Len--
		zb0001Mask |= 0x400
	}
	if z.HealResult == nil {
		zb0001Len--
		zb0001Mask |= 0x800
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "type"
		err = en.Append(0xa4, 0x74, 0x79, 0x70, 0x65)
		if err != nil {
			return
		}
		err = en.WriteUint64(uint64(z.TraceType))
		if err != nil {
			err = msgp.WrapError(err, "TraceType")
			return
		}
		// write "nodename"
		err = en.Append(0xa8, 0x6e, 0x6f, 0x64, 0x65, 0x6e, 0x61, 0x6d, 0x65)
		if err != nil {
			return
		}
		err = en.WriteString(z.NodeName)
		if err != nil {
			err = msgp.WrapError(err, "NodeName")
			return
		}
		// write "funcname"
		err = en.Append(0xa8, 0x66, 0x75, 0x6e, 0x63, 0x6e, 0x61, 0x6d, 0x65)
		if err != nil {
			return
		}
		err = en.WriteString(z.FuncName)
		if err != nil {
			err = msgp.WrapError(err, "FuncName")
			return
		}
		// write "time"
		err = en.Append(0xa4, 0x74, 0x69, 0x6d, 0x65)
		if err != nil {
			return
		}
		err = en.WriteTime(z.Time)
		if err != nil {
			err = msgp.WrapError(err, "Time")
			return
		}
		// write "path"
		err = en.Append(0xa4, 0x70, 0x61, 0x74, 0x68)
		if err != nil {
			return
		}
		err = en.WriteString(z.Path)
		if err != nil {
			err = msgp.WrapError(err, "Path")
			return
		}
		// write "dur"
		err = en.Append(0xa3, 0x64, 0x75, 0x72)
		if err != nil {
			return
		}
		err = en.WriteDuration(z.Duration)
		if err != nil {
			err = msgp.WrapError(err, "Duration")
			return
		}
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// write "bytes"
			err = en.Append(0xa5, 0x62, 0x79, 0x74, 0x65, 0x73)
			if err != nil {
				return
			}
			err = en.WriteInt64(z.Bytes)
			if err != nil {
				err = msgp.WrapError(err, "Bytes")
				return
			}
		}
		if (zb0001Mask & 0x80) == 0 { // if not omitted
			// write "msg"
			err = en.Append(0xa3, 0x6d, 0x73, 0x67)
			if err != nil {
				return
			}
			err = en.WriteString(z.Message)
			if err != nil {
				err = msgp.WrapError(err, "Message")
				return
			}
		}
		if (zb0001Mask & 0x100) == 0 { // if not omitted
			// write "error"
			err = en.Append(0xa5, 0x65, 0x72, 0x72, 0x6f, 0x72)
			if err != nil {
				return
			}
			err = en.WriteString(z.Error)
			if err != nil {
				err = msgp.WrapError(err, "Error")
				return
			}
		}
		if (zb0001Mask & 0x200) == 0 { // if not omitted
			// write "custom"
			err = en.Append(0xa6, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d)
			if err != nil {
				return
			}
			err = en.WriteMapHeader(uint32(len(z.Custom)))
			if err != nil {
				err = msgp.WrapError(err, "Custom")
				return
			}
			for za0001, za0002 := range z.Custom {
				err = en.WriteString(za0001)
				if err != nil {
					err = msgp.WrapError(err, "Custom")
					return
				}
				err = en.WriteString(za0002)
				if err != nil {
					err = msgp.WrapError(err, "Custom", za0001)
					return
				}
			}
		}
		if (zb0001Mask & 0x400) == 0 { // if not omitted
			// write "http"
			err = en.Append(0xa4, 0x68, 0x74, 0x74, 0x70)
			if err != nil {
				return
			}
			if z.HTTP == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				// map header, size 3
				// write "request"
				err = en.Append(0x83, 0xa7, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74)
				if err != nil {
					return
				}
				err = z.HTTP.ReqInfo.EncodeMsg(en)
				if err != nil {
					err = msgp.WrapError(err, "HTTP", "ReqInfo")
					return
				}
				// write "response"
				err = en.Append(0xa8, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65)
				if err != nil {
					return
				}
				err = z.HTTP.RespInfo.EncodeMsg(en)
				if err != nil {
					err = msgp.WrapError(err, "HTTP", "RespInfo")
					return
				}
				// write "stats"
				err = en.Append(0xa5, 0x73, 0x74, 0x61, 0x74, 0x73)
				if err != nil {
					return
				}
				err = z.HTTP.CallStats.EncodeMsg(en)
				if err != nil {
					err = msgp.WrapError(err, "HTTP", "CallStats")
					return
				}
			}
		}
		if (zb0001Mask & 0x800) == 0 { // if not omitted
			// write "healResult"
			err = en.Append(0xaa, 0x68, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74)
			if err != nil {
				return
			}
			if z.HealResult == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = z.HealResult.EncodeMsg(en)
				if err != nil {
					err = msgp.WrapError(err, "HealResult")
					return
				}
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *TraceInfo) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(12)
	var zb0001Mask uint16 /* 12 bits */
	_ = zb0001Mask
	if z.Bytes == 0 {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	if z.Message == "" {
		zb0001Len--
		zb0001Mask |= 0x80
	}
	if z.Error == "" {
		zb0001Len--
		zb0001Mask |= 0x100
	}
	if z.Custom == nil {
		zb0001Len--
		zb0001Mask |= 0x200
	}
	if z.HTTP == nil {
		zb0001Len--
		zb0001Mask |= 0x400
	}
	if z.HealResult == nil {
		zb0001Len--
		zb0001Mask |= 0x800
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// string "type"
		o = append(o, 0xa4, 0x74, 0x79, 0x70, 0x65)
		o = msgp.AppendUint64(o, uint64(z.TraceType))
		// string "nodename"
		o = append(o, 0xa8, 0x6e, 0x6f, 0x64, 0x65, 0x6e, 0x61, 0x6d, 0x65)
		o = msgp.AppendString(o, z.NodeName)
		// string "funcname"
		o = append(o, 0xa8, 0x66, 0x75, 0x6e, 0x63, 0x6e, 0x61, 0x6d, 0x65)
		o = msgp.AppendString(o, z.FuncName)
		// string "time"
		o = append(o, 0xa4, 0x74, 0x69, 0x6d, 0x65)
		o = msgp.AppendTime(o, z.Time)
		// string "path"
		o = append(o, 0xa4, 0x70, 0x61, 0x74, 0x68)
		o = msgp.AppendString(o, z.Path)
		// string "dur"
		o = append(o, 0xa3, 0x64, 0x75, 0x72)
		o = msgp.AppendDuration(o, z.Duration)
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// string "bytes"
			o = append(o, 0xa5, 0x62, 0x79, 0x74, 0x65, 0x73)
			o = msgp.AppendInt64(o, z.Bytes)
		}
		if (zb0001Mask & 0x80) == 0 { // if not omitted
			// string "msg"
			o = append(o, 0xa3, 0x6d, 0x73, 0x67)
			o = msgp.AppendString(o, z.Message)
		}
		if (zb0001Mask & 0x100) == 0 { // if not omitted
			// string "error"
			o = append(o, 0xa5, 0x65, 0x72, 0x72, 0x6f, 0x72)
			o = msgp.AppendString(o, z.Error)
		}
		if (zb0001Mask & 0x200) == 0 { // if not omitted
			// string "custom"
			o = append(o, 0xa6, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d)
			o = msgp.AppendMapHeader(o, uint32(len(z.Custom)))
			for za0001, za0002 := range z.Custom {
				o = msgp.AppendString(o, za0001)
				o = msgp.AppendString(o, za0002)
			}
		}
		if (zb0001Mask & 0x400) == 0 { // if not omitted
			// string "http"
			o = append(o, 0xa4, 0x68, 0x74, 0x74, 0x70)
			if z.HTTP == nil {
				o = msgp.AppendNil(o)
			} else {
				// map header, size 3
				// string "request"
				o = append(o, 0x83, 0xa7, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74)
				o, err = z.HTTP.ReqInfo.MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "HTTP", "ReqInfo")
					return
				}
				// string "response"
				o = append(o, 0xa8, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65)
				o, err = z.HTTP.RespInfo.MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "HTTP", "RespInfo")
					return
				}
				// string "stats"
				o = append(o, 0xa5, 0x73, 0x74, 0x61, 0x74, 0x73)
				o, err = z.HTTP.CallStats.MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "HTTP", "CallStats")
					return
				}
			}
		}
		if (zb0001Mask & 0x800) == 0 { // if not omitted
			// string "healResult"
			o = append(o, 0xaa, 0x68, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74)
			if z.HealResult == nil {
				o = msgp.AppendNil(o)
			} else {
				o, err = z.HealResult.MarshalMsg(o)
				if err != nil {
					err = msgp.WrapError(err, "HealResult")
					return
				}
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *TraceInfo) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 6 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "type":
			{
				var zb0002 uint64
				zb0002, bts, err = msgp.ReadUint64Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "TraceType")
					return
				}
				z.TraceType = TraceType(zb0002)
			}
		case "nodename":
			z.NodeName, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "NodeName")
				return
			}
		case "funcname":
			z.FuncName, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "FuncName")
				return
			}
		case "time":
			z.Time, bts, err = msgp.ReadTimeUTCBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Time")
				return
			}
		case "path":
			z.Path, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Path")
				return
			}
		case "dur":
			z.Duration, bts, err = msgp.ReadDurationBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Duration")
				return
			}
		case "bytes":
			z.Bytes, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Bytes")
				return
			}
			zb0001Mask |= 0x1
		case "msg":
			z.Message, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Message")
				return
			}
			zb0001Mask |= 0x2
		case "error":
			z.Error, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Error")
				return
			}
			zb0001Mask |= 0x4
		case "custom":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Custom")
				return
			}
			if z.Custom == nil {
				z.Custom = make(map[string]string, zb0003)
			} else if len(z.Custom) > 0 {
				clear(z.Custom)
			}
			for zb0003 > 0 {
				var za0002 string
				zb0003--
				var za0001 string
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Custom")
					return
				}
				za0002, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Custom", za0001)
					return
				}
				z.Custom[za0001] = za0002
			}
			zb0001Mask |= 0x8
		case "http":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.HTTP = nil
			} else {
				if z.HTTP == nil {
					z.HTTP = new(TraceHTTPStats)
				}
				var zb0004 uint32
				zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "HTTP")
					return
				}
				for zb0004 > 0 {
					zb0004--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "HTTP")
						return
					}
					switch msgp.UnsafeString(field) {
					case "request":
						bts, err = z.HTTP.ReqInfo.UnmarshalMsg(bts)
						if err != nil {
							err = msgp.WrapError(err, "HTTP", "ReqInfo")
							return
						}
					case "response":
						bts, err = z.HTTP.RespInfo.UnmarshalMsg(bts)
						if err != nil {
							err = msgp.WrapError(err, "HTTP", "RespInfo")
							return
						}
					case "stats":
						bts, err = z.HTTP.CallStats.UnmarshalMsg(bts)
						if err != nil {
							err = msgp.WrapError(err, "HTTP", "CallStats")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "HTTP")
							return
						}
					}
				}
			}
			zb0001Mask |= 0x10
		case "healResult":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.HealResult = nil
			} else {
				if z.HealResult == nil {
					z.HealResult = new(HealResultItem)
				}
				bts, err = z.HealResult.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "HealResult")
					return
				}
			}
			zb0001Mask |= 0x20
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0x3f {
		if (zb0001Mask & 0x1) == 0 {
			z.Bytes = 0
		}
		if (zb0001Mask & 0x2) == 0 {
			z.Message = ""
		}
		if (zb0001Mask & 0x4) == 0 {
			z.Error = ""
		}
		if (zb0001Mask & 0x8) == 0 {
			z.Custom = nil
		}
		if (zb0001Mask & 0x10) == 0 {
			z.HTTP = nil
		}
		if (zb0001Mask & 0x20) == 0 {
			z.HealResult = nil
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *TraceInfo) Msgsize() (s int) {
	s = 1 + 5 + msgp.Uint64Size + 9 + msgp.StringPrefixSize + len(z.NodeName) + 9 + msgp.StringPrefixSize + len(z.FuncName) + 5 + msgp.TimeSize + 5 + msgp.StringPrefixSize + len(z.Path) + 4 + msgp.DurationSize + 6 + msgp.Int64Size + 4 + msgp.StringPrefixSize + len(z.Message) + 6 + msgp.StringPrefixSize + len(z.Error) + 7 + msgp.MapHeaderSize
	if z.Custom != nil {
		for za0001, za0002 := range z.Custom {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + msgp.StringPrefixSize + len(za0002)
		}
	}
	s += 5
	if z.HTTP == nil {
		s += msgp.NilSize
	} else {
		s += 1 + 8 + z.HTTP.ReqInfo.Msgsize() + 9 + z.HTTP.RespInfo.Msgsize() + 6 + z.HTTP.CallStats.Msgsize()
	}
	s += 11
	if z.HealResult == nil {
		s += msgp.NilSize
	} else {
		s += z.HealResult.Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *TraceRequestInfo) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 4 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "time":
			z.Time, err = dc.ReadTimeUTC()
			if err != nil {
				err = msgp.WrapError(err, "Time")
				return
			}
		case "proto":
			z.Proto, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Proto")
				return
			}
		case "method":
			z.Method, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Method")
				return
			}
		case "path":
			z.Path, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Path")
				return
			}
			zb0001Mask |= 0x1
		case "rawquery":
			z.RawQuery, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "RawQuery")
				return
			}
			zb0001Mask |= 0x2
		case "headers":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Headers")
				return
			}
			if z.Headers == nil {
				z.Headers = make(map[string][]string, zb0002)
			} else if len(z.Headers) > 0 {
				clear(z.Headers)
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Headers")
					return
				}
				var za0002 []string
				var zb0003 uint32
				zb0003, err = dc.ReadArrayHeader()
				if err != nil {
					err = msgp.WrapError(err, "Headers", za0001)
					return
				}
				if cap(za0002) >= int(zb0003) {
					za0002 = (za0002)[:zb0003]
				} else {
					za0002 = make([]string, zb0003)
				}
				for za0003 := range za0002 {
					za0002[za0003], err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Headers", za0001, za0003)
						return
					}
				}
				z.Headers[za0001] = za0002
			}
			zb0001Mask |= 0x4
		case "body":
			z.Body, err = dc.ReadBytes(z.Body)
			if err != nil {
				err = msgp.WrapError(err, "Body")
				return
			}
			zb0001Mask |= 0x8
		case "client":
			z.Client, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Client")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0xf {
		if (zb0001Mask & 0x1) == 0 {
			z.Path = ""
		}
		if (zb0001Mask & 0x2) == 0 {
			z.RawQuery = ""
		}
		if (zb0001Mask & 0x4) == 0 {
			z.Headers = nil
		}
		if (zb0001Mask & 0x8) == 0 {
			z.Body = nil
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *TraceRequestInfo) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(8)
	var zb0001Mask uint8 /* 8 bits */
	_ = zb0001Mask
	if z.Path == "" {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.RawQuery == "" {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.Headers == nil {
		zb0001Len--
		zb0001Mask |= 0x20
	}
	if z.Body == nil {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "time"
		err = en.Append(0xa4, 0x74, 0x69, 0x6d, 0x65)
		if err != nil {
			return
		}
		err = en.WriteTime(z.Time)
		if err != nil {
			err = msgp.WrapError(err, "Time")
			return
		}
		// write "proto"
		err = en.Append(0xa5, 0x70, 0x72, 0x6f, 0x74, 0x6f)
		if err != nil {
			return
		}
		err = en.WriteString(z.Proto)
		if err != nil {
			err = msgp.WrapError(err, "Proto")
			return
		}
		// write "method"
		err = en.Append(0xa6, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64)
		if err != nil {
			return
		}
		err = en.WriteString(z.Method)
		if err != nil {
			err = msgp.WrapError(err, "Method")
			return
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// write "path"
			err = en.Append(0xa4, 0x70, 0x61, 0x74, 0x68)
			if err != nil {
				return
			}
			err = en.WriteString(z.Path)
			if err != nil {
				err = msgp.WrapError(err, "Path")
				return
			}
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// write "rawquery"
			err = en.Append(0xa8, 0x72, 0x61, 0x77, 0x71, 0x75, 0x65, 0x72, 0x79)
			if err != nil {
				return
			}
			err = en.WriteString(z.RawQuery)
			if err != nil {
				err = msgp.WrapError(err, "RawQuery")
				return
			}
		}
		if (zb0001Mask & 0x20) == 0 { // if not omitted
			// write "headers"
			err = en.Append(0xa7, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73)
			if err != nil {
				return
			}
			err = en.WriteMapHeader(uint32(len(z.Headers)))
			if err != nil {
				err = msgp.WrapError(err, "Headers")
				return
			}
			for za0001, za0002 := range z.Headers {
				err = en.WriteString(za0001)
				if err != nil {
					err = msgp.WrapError(err, "Headers")
					return
				}
				err = en.WriteArrayHeader(uint32(len(za0002)))
				if err != nil {
					err = msgp.WrapError(err, "Headers", za0001)
					return
				}
				for za0003 := range za0002 {
					err = en.WriteString(za0002[za0003])
					if err != nil {
						err = msgp.WrapError(err, "Headers", za0001, za0003)
						return
					}
				}
			}
		}
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// write "body"
			err = en.Append(0xa4, 0x62, 0x6f, 0x64, 0x79)
			if err != nil {
				return
			}
			err = en.WriteBytes(z.Body)
			if err != nil {
				err = msgp.WrapError(err, "Body")
				return
			}
		}
		// write "client"
		err = en.Append(0xa6, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74)
		if err != nil {
			return
		}
		err = en.WriteString(z.Client)
		if err != nil {
			err = msgp.WrapError(err, "Client")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *TraceRequestInfo) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(8)
	var zb0001Mask uint8 /* 8 bits */
	_ = zb0001Mask
	if z.Path == "" {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.RawQuery == "" {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.Headers == nil {
		zb0001Len--
		zb0001Mask |= 0x20
	}
	if z.Body == nil {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// string "time"
		o = append(o, 0xa4, 0x74, 0x69, 0x6d, 0x65)
		o = msgp.AppendTime(o, z.Time)
		// string "proto"
		o = append(o, 0xa5, 0x70, 0x72, 0x6f, 0x74, 0x6f)
		o = msgp.AppendString(o, z.Proto)
		// string "method"
		o = append(o, 0xa6, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64)
		o = msgp.AppendString(o, z.Method)
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// string "path"
			o = append(o, 0xa4, 0x70, 0x61, 0x74, 0x68)
			o = msgp.AppendString(o, z.Path)
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// string "rawquery"
			o = append(o, 0xa8, 0x72, 0x61, 0x77, 0x71, 0x75, 0x65, 0x72, 0x79)
			o = msgp.AppendString(o, z.RawQuery)
		}
		if (zb0001Mask & 0x20) == 0 { // if not omitted
			// string "headers"
			o = append(o, 0xa7, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73)
			o = msgp.AppendMapHeader(o, uint32(len(z.Headers)))
			for za0001, za0002 := range z.Headers {
				o = msgp.AppendString(o, za0001)
				o = msgp.AppendArrayHeader(o, uint32(len(za0002)))
				for za0003 := range za0002 {
					o = msgp.AppendString(o, za0002[za0003])
				}
			}
		}
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// string "body"
			o = append(o, 0xa4, 0x62, 0x6f, 0x64, 0x79)
			o = msgp.AppendBytes(o, z.Body)
		}
		// string "client"
		o = append(o, 0xa6, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74)
		o = msgp.AppendString(o, z.Client)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *TraceRequestInfo) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 4 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "time":
			z.Time, bts, err = msgp.ReadTimeUTCBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Time")
				return
			}
		case "proto":
			z.Proto, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Proto")
				return
			}
		case "method":
			z.Method, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Method")
				return
			}
		case "path":
			z.Path, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Path")
				return
			}
			zb0001Mask |= 0x1
		case "rawquery":
			z.RawQuery, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "RawQuery")
				return
			}
			zb0001Mask |= 0x2
		case "headers":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Headers")
				return
			}
			if z.Headers == nil {
				z.Headers = make(map[string][]string, zb0002)
			} else if len(z.Headers) > 0 {
				clear(z.Headers)
			}
			for zb0002 > 0 {
				var za0002 []string
				zb0002--
				var za0001 string
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Headers")
					return
				}
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Headers", za0001)
					return
				}
				if cap(za0002) >= int(zb0003) {
					za0002 = (za0002)[:zb0003]
				} else {
					za0002 = make([]string, zb0003)
				}
				for za0003 := range za0002 {
					za0002[za0003], bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Headers", za0001, za0003)
						return
					}
				}
				z.Headers[za0001] = za0002
			}
			zb0001Mask |= 0x4
		case "body":
			z.Body, bts, err = msgp.ReadBytesBytes(bts, z.Body)
			if err != nil {
				err = msgp.WrapError(err, "Body")
				return
			}
			zb0001Mask |= 0x8
		case "client":
			z.Client, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Client")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0xf {
		if (zb0001Mask & 0x1) == 0 {
			z.Path = ""
		}
		if (zb0001Mask & 0x2) == 0 {
			z.RawQuery = ""
		}
		if (zb0001Mask & 0x4) == 0 {
			z.Headers = nil
		}
		if (zb0001Mask & 0x8) == 0 {
			z.Body = nil
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *TraceRequestInfo) Msgsize() (s int) {
	s = 1 + 5 + msgp.TimeSize + 6 + msgp.StringPrefixSize + len(z.Proto) + 7 + msgp.StringPrefixSize + len(z.Method) + 5 + msgp.StringPrefixSize + len(z.Path) + 9 + msgp.StringPrefixSize + len(z.RawQuery) + 8 + msgp.MapHeaderSize
	if z.Headers != nil {
		for za0001, za0002 := range z.Headers {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + msgp.ArrayHeaderSize
			for za0003 := range za0002 {
				s += msgp.StringPrefixSize + len(za0002[za0003])
			}
		}
	}
	s += 5 + msgp.BytesPrefixSize + len(z.Body) + 7 + msgp.StringPrefixSize + len(z.Client)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *TraceResponseInfo) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 3 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "time":
			z.Time, err = dc.ReadTimeUTC()
			if err != nil {
				err = msgp.WrapError(err, "Time")
				return
			}
		case "headers":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Headers")
				return
			}
			if z.Headers == nil {
				z.Headers = make(map[string][]string, zb0002)
			} else if len(z.Headers) > 0 {
				clear(z.Headers)
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Headers")
					return
				}
				var za0002 []string
				var zb0003 uint32
				zb0003, err = dc.ReadArrayHeader()
				if err != nil {
					err = msgp.WrapError(err, "Headers", za0001)
					return
				}
				if cap(za0002) >= int(zb0003) {
					za0002 = (za0002)[:zb0003]
				} else {
					za0002 = make([]string, zb0003)
				}
				for za0003 := range za0002 {
					za0002[za0003], err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Headers", za0001, za0003)
						return
					}
				}
				z.Headers[za0001] = za0002
			}
			zb0001Mask |= 0x1
		case "body":
			z.Body, err = dc.ReadBytes(z.Body)
			if err != nil {
				err = msgp.WrapError(err, "Body")
				return
			}
			zb0001Mask |= 0x2
		case "statuscode":
			z.StatusCode, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "StatusCode")
				return
			}
			zb0001Mask |= 0x4
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0x7 {
		if (zb0001Mask & 0x1) == 0 {
			z.Headers = nil
		}
		if (zb0001Mask & 0x2) == 0 {
			z.Body = nil
		}
		if (zb0001Mask & 0x4) == 0 {
			z.StatusCode = 0
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *TraceResponseInfo) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(4)
	var zb0001Mask uint8 /* 4 bits */
	_ = zb0001Mask
	if z.Headers == nil {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Body == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.StatusCode == 0 {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "time"
		err = en.Append(0xa4, 0x74, 0x69, 0x6d, 0x65)
		if err != nil {
			return
		}
		err = en.WriteTime(z.Time)
		if err != nil {
			err = msgp.WrapError(err, "Time")
			return
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// write "headers"
			err = en.Append(0xa7, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73)
			if err != nil {
				return
			}
			err = en.WriteMapHeader(uint32(len(z.Headers)))
			if err != nil {
				err = msgp.WrapError(err, "Headers")
				return
			}
			for za0001, za0002 := range z.Headers {
				err = en.WriteString(za0001)
				if err != nil {
					err = msgp.WrapError(err, "Headers")
					return
				}
				err = en.WriteArrayHeader(uint32(len(za0002)))
				if err != nil {
					err = msgp.WrapError(err, "Headers", za0001)
					return
				}
				for za0003 := range za0002 {
					err = en.WriteString(za0002[za0003])
					if err != nil {
						err = msgp.WrapError(err, "Headers", za0001, za0003)
						return
					}
				}
			}
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "body"
			err = en.Append(0xa4, 0x62, 0x6f, 0x64, 0x79)
			if err != nil {
				return
			}
			err = en.WriteBytes(z.Body)
			if err != nil {
				err = msgp.WrapError(err, "Body")
				return
			}
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// write "statuscode"
			err = en.Append(0xaa, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x63, 0x6f, 0x64, 0x65)
			if err != nil {
				return
			}
			err = en.WriteInt(z.StatusCode)
			if err != nil {
				err = msgp.WrapError(err, "StatusCode")
				return
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *TraceResponseInfo) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(4)
	var zb0001Mask uint8 /* 4 bits */
	_ = zb0001Mask
	if z.Headers == nil {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Body == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.StatusCode == 0 {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// string "time"
		o = append(o, 0xa4, 0x74, 0x69, 0x6d, 0x65)
		o = msgp.AppendTime(o, z.Time)
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// string "headers"
			o = append(o, 0xa7, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73)
			o = msgp.AppendMapHeader(o, uint32(len(z.Headers)))
			for za0001, za0002 := range z.Headers {
				o = msgp.AppendString(o, za0001)
				o = msgp.AppendArrayHeader(o, uint32(len(za0002)))
				for za0003 := range za0002 {
					o = msgp.AppendString(o, za0002[za0003])
				}
			}
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "body"
			o = append(o, 0xa4, 0x62, 0x6f, 0x64, 0x79)
			o = msgp.AppendBytes(o, z.Body)
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// string "statuscode"
			o = append(o, 0xaa, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x63, 0x6f, 0x64, 0x65)
			o = msgp.AppendInt(o, z.StatusCode)
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *TraceResponseInfo) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	var zb0001Mask uint8 /* 3 bits */
	_ = zb0001Mask
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "time":
			z.Time, bts, err = msgp.ReadTimeUTCBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Time")
				return
			}
		case "headers":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Headers")
				return
			}
			if z.Headers == nil {
				z.Headers = make(map[string][]string, zb0002)
			} else if len(z.Headers) > 0 {
				clear(z.Headers)
			}
			for zb0002 > 0 {
				var za0002 []string
				zb0002--
				var za0001 string
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Headers")
					return
				}
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Headers", za0001)
					return
				}
				if cap(za0002) >= int(zb0003) {
					za0002 = (za0002)[:zb0003]
				} else {
					za0002 = make([]string, zb0003)
				}
				for za0003 := range za0002 {
					za0002[za0003], bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Headers", za0001, za0003)
						return
					}
				}
				z.Headers[za0001] = za0002
			}
			zb0001Mask |= 0x1
		case "body":
			z.Body, bts, err = msgp.ReadBytesBytes(bts, z.Body)
			if err != nil {
				err = msgp.WrapError(err, "Body")
				return
			}
			zb0001Mask |= 0x2
		case "statuscode":
			z.StatusCode, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "StatusCode")
				return
			}
			zb0001Mask |= 0x4
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	// Clear omitted fields.
	if zb0001Mask != 0x7 {
		if (zb0001Mask & 0x1) == 0 {
			z.Headers = nil
		}
		if (zb0001Mask & 0x2) == 0 {
			z.Body = nil
		}
		if (zb0001Mask & 0x4) == 0 {
			z.StatusCode = 0
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *TraceResponseInfo) Msgsize() (s int) {
	s = 1 + 5 + msgp.TimeSize + 8 + msgp.MapHeaderSize
	if z.Headers != nil {
		for za0001, za0002 := range z.Headers {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + msgp.ArrayHeaderSize
			for za0003 := range za0002 {
				s += msgp.StringPrefixSize + len(za0002[za0003])
			}
		}
	}
	s += 5 + msgp.BytesPrefixSize + len(z.Body) + 11 + msgp.IntSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *TraceType) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 uint64
		zb0001, err = dc.ReadUint64()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = TraceType(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z TraceType) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteUint64(uint64(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z TraceType) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendUint64(o, uint64(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *TraceType) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 uint64
		zb0001, bts, err = msgp.ReadUint64Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = TraceType(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z TraceType) Msgsize() (s int) {
	s = msgp.Uint64Size
	return
}
